package com.bdx.rainbow.mapper.urs;

import com.bdx.rainbow.entity.urs.SysDeptExtHis;
import com.bdx.rainbow.entity.urs.SysDeptExtHisExample;
import com.bdx.rainbow.entity.urs.SysDeptExtHisKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDeptExtHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int countByExample(SysDeptExtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int deleteByExample(SysDeptExtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int deleteByPrimaryKey(SysDeptExtHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int insert(SysDeptExtHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int insertSelective(SysDeptExtHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    List<SysDeptExtHis> selectByExample(SysDeptExtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    SysDeptExtHis selectByPrimaryKey(SysDeptExtHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysDeptExtHis record, @Param("example") SysDeptExtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int updateByExample(@Param("record") SysDeptExtHis record, @Param("example") SysDeptExtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int updateByPrimaryKeySelective(SysDeptExtHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    int updateByPrimaryKey(SysDeptExtHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dept_ext_his
     *
     * @mbggenerated Tue Jan 19 22:26:19 CST 2016
     */
    void insertBatch(List<SysDeptExtHis> recordLst);
}