package com.bdx.rainbow.mapper.urs;

import com.bdx.rainbow.entity.urs.SysMenuHis;
import com.bdx.rainbow.entity.urs.SysMenuHisExample;
import com.bdx.rainbow.entity.urs.SysMenuHisKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int countByExample(SysMenuHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int deleteByExample(SysMenuHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int deleteByPrimaryKey(SysMenuHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int insert(SysMenuHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int insertSelective(SysMenuHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    List<SysMenuHis> selectByExample(SysMenuHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    SysMenuHis selectByPrimaryKey(SysMenuHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysMenuHis record, @Param("example") SysMenuHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int updateByExample(@Param("record") SysMenuHis record, @Param("example") SysMenuHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int updateByPrimaryKeySelective(SysMenuHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    int updateByPrimaryKey(SysMenuHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu_his
     *
     * @mbggenerated Fri Mar 11 20:26:59 CST 2016
     */
    void insertBatch(List<SysMenuHis> recordLst);
}