package com.bdx.rainbow.mapper.urs;

import com.bdx.rainbow.entity.urs.SysViews;
import com.bdx.rainbow.entity.urs.SysViewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_views
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    int countByExample(SysViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_views
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    int deleteByExample(SysViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_views
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    int insert(SysViews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_views
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    int insertSelective(SysViews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_views
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    List<SysViews> selectByExample(SysViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_views
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysViews record, @Param("example") SysViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_views
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    int updateByExample(@Param("record") SysViews record, @Param("example") SysViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_sys_views
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    void insertBatch(List<SysViews> recordLst);
}