package com.bdx.rainbow.entity.ydzf;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class TYdzfInspectCaseWitnessesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected String suffix = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected int limitClauseStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected int limitClauseCount = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public TYdzfInspectCaseWitnessesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setLimitClauseStart(int limitClauseStart) {
        this.limitClauseStart=limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public int getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setLimitClauseCount(int limitClauseCount) {
        this.limitClauseCount=limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public int getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInspectCaseWitnessesIdIsNull() {
            addCriterion("INSPECT_CASE_WITNESSES_ID is null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdIsNotNull() {
            addCriterion("INSPECT_CASE_WITNESSES_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID =", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdNotEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID <>", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdGreaterThan(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID >", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID >=", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdLessThan(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID <", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID <=", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_WITNESSES_ID in", values, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdNotIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_WITNESSES_ID not in", values, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_WITNESSES_ID between", value1, value2, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_WITNESSES_ID not between", value1, value2, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdIsNull() {
            addCriterion("INSPECT_CASE_ID is null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdIsNotNull() {
            addCriterion("INSPECT_CASE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_ID =", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdNotEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_ID <>", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdGreaterThan(Integer value) {
            addCriterion("INSPECT_CASE_ID >", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_ID >=", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdLessThan(Integer value) {
            addCriterion("INSPECT_CASE_ID <", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_ID <=", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_ID in", values, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdNotIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_ID not in", values, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_ID between", value1, value2, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_ID not between", value1, value2, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateIsNull() {
            addCriterion("WITNESSES_DATE is null");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateIsNotNull() {
            addCriterion("WITNESSES_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateEqualTo(Timestamp value) {
            addCriterion("WITNESSES_DATE =", value, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateNotEqualTo(Timestamp value) {
            addCriterion("WITNESSES_DATE <>", value, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateGreaterThan(Timestamp value) {
            addCriterion("WITNESSES_DATE >", value, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("WITNESSES_DATE >=", value, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateLessThan(Timestamp value) {
            addCriterion("WITNESSES_DATE <", value, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateLessThanOrEqualTo(Timestamp value) {
            addCriterion("WITNESSES_DATE <=", value, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateIn(List<Timestamp> values) {
            addCriterion("WITNESSES_DATE in", values, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateNotIn(List<Timestamp> values) {
            addCriterion("WITNESSES_DATE not in", values, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateBetween(Timestamp value1, Timestamp value2) {
            addCriterion("WITNESSES_DATE between", value1, value2, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesDateNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("WITNESSES_DATE not between", value1, value2, "witnessesDate");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsIsNull() {
            addCriterion("WITNESSES_VIDEO_IDS is null");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsIsNotNull() {
            addCriterion("WITNESSES_VIDEO_IDS is not null");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsEqualTo(String value) {
            addCriterion("WITNESSES_VIDEO_IDS =", value, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsNotEqualTo(String value) {
            addCriterion("WITNESSES_VIDEO_IDS <>", value, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsGreaterThan(String value) {
            addCriterion("WITNESSES_VIDEO_IDS >", value, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsGreaterThanOrEqualTo(String value) {
            addCriterion("WITNESSES_VIDEO_IDS >=", value, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsLessThan(String value) {
            addCriterion("WITNESSES_VIDEO_IDS <", value, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsLessThanOrEqualTo(String value) {
            addCriterion("WITNESSES_VIDEO_IDS <=", value, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsLike(String value) {
            addCriterion("WITNESSES_VIDEO_IDS like", value, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsNotLike(String value) {
            addCriterion("WITNESSES_VIDEO_IDS not like", value, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsIn(List<String> values) {
            addCriterion("WITNESSES_VIDEO_IDS in", values, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsNotIn(List<String> values) {
            addCriterion("WITNESSES_VIDEO_IDS not in", values, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsBetween(String value1, String value2) {
            addCriterion("WITNESSES_VIDEO_IDS between", value1, value2, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesVideoIdsNotBetween(String value1, String value2) {
            addCriterion("WITNESSES_VIDEO_IDS not between", value1, value2, "witnessesVideoIds");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultIsNull() {
            addCriterion("WITNESSES_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultIsNotNull() {
            addCriterion("WITNESSES_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultEqualTo(String value) {
            addCriterion("WITNESSES_RESULT =", value, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultNotEqualTo(String value) {
            addCriterion("WITNESSES_RESULT <>", value, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultGreaterThan(String value) {
            addCriterion("WITNESSES_RESULT >", value, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultGreaterThanOrEqualTo(String value) {
            addCriterion("WITNESSES_RESULT >=", value, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultLessThan(String value) {
            addCriterion("WITNESSES_RESULT <", value, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultLessThanOrEqualTo(String value) {
            addCriterion("WITNESSES_RESULT <=", value, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultLike(String value) {
            addCriterion("WITNESSES_RESULT like", value, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultNotLike(String value) {
            addCriterion("WITNESSES_RESULT not like", value, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultIn(List<String> values) {
            addCriterion("WITNESSES_RESULT in", values, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultNotIn(List<String> values) {
            addCriterion("WITNESSES_RESULT not in", values, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultBetween(String value1, String value2) {
            addCriterion("WITNESSES_RESULT between", value1, value2, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesResultNotBetween(String value1, String value2) {
            addCriterion("WITNESSES_RESULT not between", value1, value2, "witnessesResult");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceIsNull() {
            addCriterion("WITNESSES_ADVICE is null");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceIsNotNull() {
            addCriterion("WITNESSES_ADVICE is not null");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceEqualTo(String value) {
            addCriterion("WITNESSES_ADVICE =", value, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceNotEqualTo(String value) {
            addCriterion("WITNESSES_ADVICE <>", value, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceGreaterThan(String value) {
            addCriterion("WITNESSES_ADVICE >", value, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceGreaterThanOrEqualTo(String value) {
            addCriterion("WITNESSES_ADVICE >=", value, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceLessThan(String value) {
            addCriterion("WITNESSES_ADVICE <", value, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceLessThanOrEqualTo(String value) {
            addCriterion("WITNESSES_ADVICE <=", value, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceLike(String value) {
            addCriterion("WITNESSES_ADVICE like", value, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceNotLike(String value) {
            addCriterion("WITNESSES_ADVICE not like", value, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceIn(List<String> values) {
            addCriterion("WITNESSES_ADVICE in", values, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceNotIn(List<String> values) {
            addCriterion("WITNESSES_ADVICE not in", values, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceBetween(String value1, String value2) {
            addCriterion("WITNESSES_ADVICE between", value1, value2, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andWitnessesAdviceNotBetween(String value1, String value2) {
            addCriterion("WITNESSES_ADVICE not between", value1, value2, "witnessesAdvice");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Timestamp value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Timestamp value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Timestamp> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Timestamp> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIsNull() {
            addCriterion("CREATE_USERID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIsNotNull() {
            addCriterion("CREATE_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUseridEqualTo(Integer value) {
            addCriterion("CREATE_USERID =", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotEqualTo(Integer value) {
            addCriterion("CREATE_USERID <>", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridGreaterThan(Integer value) {
            addCriterion("CREATE_USERID >", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATE_USERID >=", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridLessThan(Integer value) {
            addCriterion("CREATE_USERID <", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridLessThanOrEqualTo(Integer value) {
            addCriterion("CREATE_USERID <=", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIn(List<Integer> values) {
            addCriterion("CREATE_USERID in", values, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotIn(List<Integer> values) {
            addCriterion("CREATE_USERID not in", values, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_USERID between", value1, value2, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_USERID not between", value1, value2, "createUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Timestamp value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Timestamp value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Timestamp value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Timestamp value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Timestamp> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Timestamp> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIsNull() {
            addCriterion("UPDATE_USERID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIsNotNull() {
            addCriterion("UPDATE_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridEqualTo(Integer value) {
            addCriterion("UPDATE_USERID =", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotEqualTo(Integer value) {
            addCriterion("UPDATE_USERID <>", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridGreaterThan(Integer value) {
            addCriterion("UPDATE_USERID >", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("UPDATE_USERID >=", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridLessThan(Integer value) {
            addCriterion("UPDATE_USERID <", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridLessThanOrEqualTo(Integer value) {
            addCriterion("UPDATE_USERID <=", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIn(List<Integer> values) {
            addCriterion("UPDATE_USERID in", values, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotIn(List<Integer> values) {
            addCriterion("UPDATE_USERID not in", values, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridBetween(Integer value1, Integer value2) {
            addCriterion("UPDATE_USERID between", value1, value2, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("UPDATE_USERID not between", value1, value2, "updateUserid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}