package com.bdx.rainbow.entity.ydzf;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class TYdzfInspectCaseExecutePunishExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected String suffix = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected int limitClauseStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected int limitClauseCount = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public TYdzfInspectCaseExecutePunishExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setLimitClauseStart(int limitClauseStart) {
        this.limitClauseStart=limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public int getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setLimitClauseCount(int limitClauseCount) {
        this.limitClauseCount=limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public int getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInspectCaseExecutePunishIdIsNull() {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID is null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdIsNotNull() {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID =", value, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdNotEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID <>", value, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdGreaterThan(Integer value) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID >", value, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID >=", value, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdLessThan(Integer value) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID <", value, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID <=", value, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID in", values, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdNotIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID not in", values, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID between", value1, value2, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseExecutePunishIdNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_EXECUTE_PUNISH_ID not between", value1, value2, "inspectCaseExecutePunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdIsNull() {
            addCriterion("INSPECT_CASE_ID is null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdIsNotNull() {
            addCriterion("INSPECT_CASE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_ID =", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdNotEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_ID <>", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdGreaterThan(Integer value) {
            addCriterion("INSPECT_CASE_ID >", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_ID >=", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdLessThan(Integer value) {
            addCriterion("INSPECT_CASE_ID <", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_ID <=", value, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_ID in", values, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdNotIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_ID not in", values, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_ID between", value1, value2, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_ID not between", value1, value2, "inspectCaseId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdIsNull() {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID is null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdIsNotNull() {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID =", value, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdNotEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID <>", value, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdGreaterThan(Integer value) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID >", value, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID >=", value, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdLessThan(Integer value) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID <", value, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID <=", value, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID in", values, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdNotIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID not in", values, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID between", value1, value2, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseReadyPunishIdNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_READY_PUNISH_ID not between", value1, value2, "inspectCaseReadyPunishId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdIsNull() {
            addCriterion("INSPECT_CASE_WITNESSES_ID is null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdIsNotNull() {
            addCriterion("INSPECT_CASE_WITNESSES_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID =", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdNotEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID <>", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdGreaterThan(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID >", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID >=", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdLessThan(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID <", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECT_CASE_WITNESSES_ID <=", value, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_WITNESSES_ID in", values, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdNotIn(List<Integer> values) {
            addCriterion("INSPECT_CASE_WITNESSES_ID not in", values, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_WITNESSES_ID between", value1, value2, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andInspectCaseWitnessesIdNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECT_CASE_WITNESSES_ID not between", value1, value2, "inspectCaseWitnessesId");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodIsNull() {
            addCriterion("EXECUTE_METHOD is null");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodIsNotNull() {
            addCriterion("EXECUTE_METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodEqualTo(String value) {
            addCriterion("EXECUTE_METHOD =", value, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodNotEqualTo(String value) {
            addCriterion("EXECUTE_METHOD <>", value, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodGreaterThan(String value) {
            addCriterion("EXECUTE_METHOD >", value, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodGreaterThanOrEqualTo(String value) {
            addCriterion("EXECUTE_METHOD >=", value, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodLessThan(String value) {
            addCriterion("EXECUTE_METHOD <", value, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodLessThanOrEqualTo(String value) {
            addCriterion("EXECUTE_METHOD <=", value, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodLike(String value) {
            addCriterion("EXECUTE_METHOD like", value, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodNotLike(String value) {
            addCriterion("EXECUTE_METHOD not like", value, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodIn(List<String> values) {
            addCriterion("EXECUTE_METHOD in", values, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodNotIn(List<String> values) {
            addCriterion("EXECUTE_METHOD not in", values, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodBetween(String value1, String value2) {
            addCriterion("EXECUTE_METHOD between", value1, value2, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteMethodNotBetween(String value1, String value2) {
            addCriterion("EXECUTE_METHOD not between", value1, value2, "executeMethod");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusIsNull() {
            addCriterion("EXECUTE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusIsNotNull() {
            addCriterion("EXECUTE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusEqualTo(String value) {
            addCriterion("EXECUTE_STATUS =", value, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusNotEqualTo(String value) {
            addCriterion("EXECUTE_STATUS <>", value, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusGreaterThan(String value) {
            addCriterion("EXECUTE_STATUS >", value, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusGreaterThanOrEqualTo(String value) {
            addCriterion("EXECUTE_STATUS >=", value, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusLessThan(String value) {
            addCriterion("EXECUTE_STATUS <", value, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusLessThanOrEqualTo(String value) {
            addCriterion("EXECUTE_STATUS <=", value, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusLike(String value) {
            addCriterion("EXECUTE_STATUS like", value, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusNotLike(String value) {
            addCriterion("EXECUTE_STATUS not like", value, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusIn(List<String> values) {
            addCriterion("EXECUTE_STATUS in", values, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusNotIn(List<String> values) {
            addCriterion("EXECUTE_STATUS not in", values, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusBetween(String value1, String value2) {
            addCriterion("EXECUTE_STATUS between", value1, value2, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andExecuteStatusNotBetween(String value1, String value2) {
            addCriterion("EXECUTE_STATUS not between", value1, value2, "executeStatus");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Timestamp value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Timestamp value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Timestamp> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Timestamp> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIsNull() {
            addCriterion("CREATE_USERID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIsNotNull() {
            addCriterion("CREATE_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUseridEqualTo(Integer value) {
            addCriterion("CREATE_USERID =", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotEqualTo(Integer value) {
            addCriterion("CREATE_USERID <>", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridGreaterThan(Integer value) {
            addCriterion("CREATE_USERID >", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATE_USERID >=", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridLessThan(Integer value) {
            addCriterion("CREATE_USERID <", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridLessThanOrEqualTo(Integer value) {
            addCriterion("CREATE_USERID <=", value, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridIn(List<Integer> values) {
            addCriterion("CREATE_USERID in", values, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotIn(List<Integer> values) {
            addCriterion("CREATE_USERID not in", values, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_USERID between", value1, value2, "createUserid");
            return (Criteria) this;
        }

        public Criteria andCreateUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_USERID not between", value1, value2, "createUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Timestamp value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Timestamp value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Timestamp value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Timestamp value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Timestamp> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Timestamp> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIsNull() {
            addCriterion("UPDATE_USERID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIsNotNull() {
            addCriterion("UPDATE_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridEqualTo(Integer value) {
            addCriterion("UPDATE_USERID =", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotEqualTo(Integer value) {
            addCriterion("UPDATE_USERID <>", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridGreaterThan(Integer value) {
            addCriterion("UPDATE_USERID >", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("UPDATE_USERID >=", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridLessThan(Integer value) {
            addCriterion("UPDATE_USERID <", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridLessThanOrEqualTo(Integer value) {
            addCriterion("UPDATE_USERID <=", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIn(List<Integer> values) {
            addCriterion("UPDATE_USERID in", values, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotIn(List<Integer> values) {
            addCriterion("UPDATE_USERID not in", values, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridBetween(Integer value1, Integer value2) {
            addCriterion("UPDATE_USERID between", value1, value2, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("UPDATE_USERID not between", value1, value2, "updateUserid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ydzf_inspect_case_execute_punish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}