package com.bdx.rainbow.spsy.dal.ibatis.model;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TOriginMerchantStockOutExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected Integer limitClauseStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected Integer limitClauseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected String suffix = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public TOriginMerchantStockOutExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected TOriginMerchantStockOutExample(TOriginMerchantStockOutExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public void setLimitClauseStart(Integer limitClauseStart) {
        this.limitClauseStart = limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public Integer getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public void setLimitClauseCount(Integer limitClauseCount) {
        this.limitClauseCount = limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public Integer getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andOperationOutIdIsNull() {
            addCriterion("OPERATION_OUT_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdIsNotNull() {
            addCriterion("OPERATION_OUT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdEqualTo(Integer value) {
            addCriterion("OPERATION_OUT_ID =", value, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdNotEqualTo(Integer value) {
            addCriterion("OPERATION_OUT_ID <>", value, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdGreaterThan(Integer value) {
            addCriterion("OPERATION_OUT_ID >", value, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPERATION_OUT_ID >=", value, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdLessThan(Integer value) {
            addCriterion("OPERATION_OUT_ID <", value, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdLessThanOrEqualTo(Integer value) {
            addCriterion("OPERATION_OUT_ID <=", value, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdIn(List<Integer> values) {
            addCriterion("OPERATION_OUT_ID in", values, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdNotIn(List<Integer> values) {
            addCriterion("OPERATION_OUT_ID not in", values, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdBetween(Integer value1, Integer value2) {
            addCriterion("OPERATION_OUT_ID between", value1, value2, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andOperationOutIdNotBetween(Integer value1, Integer value2) {
            addCriterion("OPERATION_OUT_ID not between", value1, value2, "operationOutId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("SKU_ID is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("SKU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Integer value) {
            addCriterion("SKU_ID =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Integer value) {
            addCriterion("SKU_ID <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Integer value) {
            addCriterion("SKU_ID >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SKU_ID >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Integer value) {
            addCriterion("SKU_ID <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Integer value) {
            addCriterion("SKU_ID <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Integer> values) {
            addCriterion("SKU_ID in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Integer> values) {
            addCriterion("SKU_ID not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Integer value1, Integer value2) {
            addCriterion("SKU_ID between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SKU_ID not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("SKU_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("SKU_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(String value) {
            addCriterion("SKU_NAME =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(String value) {
            addCriterion("SKU_NAME <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(String value) {
            addCriterion("SKU_NAME >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_NAME >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(String value) {
            addCriterion("SKU_NAME <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(String value) {
            addCriterion("SKU_NAME <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLike(String value) {
            addCriterion("SKU_NAME like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotLike(String value) {
            addCriterion("SKU_NAME not like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<String> values) {
            addCriterion("SKU_NAME in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<String> values) {
            addCriterion("SKU_NAME not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(String value1, String value2) {
            addCriterion("SKU_NAME between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(String value1, String value2) {
            addCriterion("SKU_NAME not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeIsNull() {
            addCriterion("SKU_BAR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeIsNotNull() {
            addCriterion("SKU_BAR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeEqualTo(String value) {
            addCriterion("SKU_BAR_CODE =", value, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeNotEqualTo(String value) {
            addCriterion("SKU_BAR_CODE <>", value, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeGreaterThan(String value) {
            addCriterion("SKU_BAR_CODE >", value, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_BAR_CODE >=", value, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeLessThan(String value) {
            addCriterion("SKU_BAR_CODE <", value, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeLessThanOrEqualTo(String value) {
            addCriterion("SKU_BAR_CODE <=", value, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeLike(String value) {
            addCriterion("SKU_BAR_CODE like", value, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeNotLike(String value) {
            addCriterion("SKU_BAR_CODE not like", value, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeIn(List<String> values) {
            addCriterion("SKU_BAR_CODE in", values, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeNotIn(List<String> values) {
            addCriterion("SKU_BAR_CODE not in", values, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeBetween(String value1, String value2) {
            addCriterion("SKU_BAR_CODE between", value1, value2, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBarCodeNotBetween(String value1, String value2) {
            addCriterion("SKU_BAR_CODE not between", value1, value2, "skuBarCode");
            return (Criteria) this;
        }

        public Criteria andSkuBatchIsNull() {
            addCriterion("SKU_BATCH is null");
            return (Criteria) this;
        }

        public Criteria andSkuBatchIsNotNull() {
            addCriterion("SKU_BATCH is not null");
            return (Criteria) this;
        }

        public Criteria andSkuBatchEqualTo(String value) {
            addCriterion("SKU_BATCH =", value, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchNotEqualTo(String value) {
            addCriterion("SKU_BATCH <>", value, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchGreaterThan(String value) {
            addCriterion("SKU_BATCH >", value, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_BATCH >=", value, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchLessThan(String value) {
            addCriterion("SKU_BATCH <", value, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchLessThanOrEqualTo(String value) {
            addCriterion("SKU_BATCH <=", value, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchLike(String value) {
            addCriterion("SKU_BATCH like", value, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchNotLike(String value) {
            addCriterion("SKU_BATCH not like", value, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchIn(List<String> values) {
            addCriterion("SKU_BATCH in", values, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchNotIn(List<String> values) {
            addCriterion("SKU_BATCH not in", values, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchBetween(String value1, String value2) {
            addCriterion("SKU_BATCH between", value1, value2, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSkuBatchNotBetween(String value1, String value2) {
            addCriterion("SKU_BATCH not between", value1, value2, "skuBatch");
            return (Criteria) this;
        }

        public Criteria andSaleDateIsNull() {
            addCriterion("SALE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSaleDateIsNotNull() {
            addCriterion("SALE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSaleDateEqualTo(Timestamp value) {
            addCriterion("SALE_DATE =", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateNotEqualTo(Timestamp value) {
            addCriterion("SALE_DATE <>", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateGreaterThan(Timestamp value) {
            addCriterion("SALE_DATE >", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("SALE_DATE >=", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateLessThan(Timestamp value) {
            addCriterion("SALE_DATE <", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateLessThanOrEqualTo(Timestamp value) {
            addCriterion("SALE_DATE <=", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateIn(List<Timestamp> values) {
            addCriterion("SALE_DATE in", values, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateNotIn(List<Timestamp> values) {
            addCriterion("SALE_DATE not in", values, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateBetween(Timestamp value1, Timestamp value2) {
            addCriterion("SALE_DATE between", value1, value2, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("SALE_DATE not between", value1, value2, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityIsNull() {
            addCriterion("SALE_QUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityIsNotNull() {
            addCriterion("SALE_QUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityEqualTo(Integer value) {
            addCriterion("SALE_QUANTITY =", value, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityNotEqualTo(Integer value) {
            addCriterion("SALE_QUANTITY <>", value, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityGreaterThan(Integer value) {
            addCriterion("SALE_QUANTITY >", value, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("SALE_QUANTITY >=", value, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityLessThan(Integer value) {
            addCriterion("SALE_QUANTITY <", value, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("SALE_QUANTITY <=", value, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityIn(List<Integer> values) {
            addCriterion("SALE_QUANTITY in", values, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityNotIn(List<Integer> values) {
            addCriterion("SALE_QUANTITY not in", values, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityBetween(Integer value1, Integer value2) {
            addCriterion("SALE_QUANTITY between", value1, value2, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("SALE_QUANTITY not between", value1, value2, "saleQuantity");
            return (Criteria) this;
        }

        public Criteria andSaleUnitIsNull() {
            addCriterion("SALE_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andSaleUnitIsNotNull() {
            addCriterion("SALE_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andSaleUnitEqualTo(String value) {
            addCriterion("SALE_UNIT =", value, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitNotEqualTo(String value) {
            addCriterion("SALE_UNIT <>", value, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitGreaterThan(String value) {
            addCriterion("SALE_UNIT >", value, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitGreaterThanOrEqualTo(String value) {
            addCriterion("SALE_UNIT >=", value, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitLessThan(String value) {
            addCriterion("SALE_UNIT <", value, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitLessThanOrEqualTo(String value) {
            addCriterion("SALE_UNIT <=", value, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitLike(String value) {
            addCriterion("SALE_UNIT like", value, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitNotLike(String value) {
            addCriterion("SALE_UNIT not like", value, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitIn(List<String> values) {
            addCriterion("SALE_UNIT in", values, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitNotIn(List<String> values) {
            addCriterion("SALE_UNIT not in", values, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitBetween(String value1, String value2) {
            addCriterion("SALE_UNIT between", value1, value2, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andSaleUnitNotBetween(String value1, String value2) {
            addCriterion("SALE_UNIT not between", value1, value2, "saleUnit");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNull() {
            addCriterion("ENTERPRISE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNotNull() {
            addCriterion("ENTERPRISE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdEqualTo(Integer value) {
            addCriterion("ENTERPRISE_ID =", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotEqualTo(Integer value) {
            addCriterion("ENTERPRISE_ID <>", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThan(Integer value) {
            addCriterion("ENTERPRISE_ID >", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ENTERPRISE_ID >=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThan(Integer value) {
            addCriterion("ENTERPRISE_ID <", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThanOrEqualTo(Integer value) {
            addCriterion("ENTERPRISE_ID <=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIn(List<Integer> values) {
            addCriterion("ENTERPRISE_ID in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotIn(List<Integer> values) {
            addCriterion("ENTERPRISE_ID not in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdBetween(Integer value1, Integer value2) {
            addCriterion("ENTERPRISE_ID between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ENTERPRISE_ID not between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIsNull() {
            addCriterion("ENTERPRISE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIsNotNull() {
            addCriterion("ENTERPRISE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameEqualTo(String value) {
            addCriterion("ENTERPRISE_NAME =", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotEqualTo(String value) {
            addCriterion("ENTERPRISE_NAME <>", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameGreaterThan(String value) {
            addCriterion("ENTERPRISE_NAME >", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameGreaterThanOrEqualTo(String value) {
            addCriterion("ENTERPRISE_NAME >=", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLessThan(String value) {
            addCriterion("ENTERPRISE_NAME <", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLessThanOrEqualTo(String value) {
            addCriterion("ENTERPRISE_NAME <=", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLike(String value) {
            addCriterion("ENTERPRISE_NAME like", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotLike(String value) {
            addCriterion("ENTERPRISE_NAME not like", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIn(List<String> values) {
            addCriterion("ENTERPRISE_NAME in", values, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotIn(List<String> values) {
            addCriterion("ENTERPRISE_NAME not in", values, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameBetween(String value1, String value2) {
            addCriterion("ENTERPRISE_NAME between", value1, value2, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotBetween(String value1, String value2) {
            addCriterion("ENTERPRISE_NAME not between", value1, value2, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andManagerPersonIsNull() {
            addCriterion("MANAGER_PERSON is null");
            return (Criteria) this;
        }

        public Criteria andManagerPersonIsNotNull() {
            addCriterion("MANAGER_PERSON is not null");
            return (Criteria) this;
        }

        public Criteria andManagerPersonEqualTo(String value) {
            addCriterion("MANAGER_PERSON =", value, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonNotEqualTo(String value) {
            addCriterion("MANAGER_PERSON <>", value, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonGreaterThan(String value) {
            addCriterion("MANAGER_PERSON >", value, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonGreaterThanOrEqualTo(String value) {
            addCriterion("MANAGER_PERSON >=", value, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonLessThan(String value) {
            addCriterion("MANAGER_PERSON <", value, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonLessThanOrEqualTo(String value) {
            addCriterion("MANAGER_PERSON <=", value, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonLike(String value) {
            addCriterion("MANAGER_PERSON like", value, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonNotLike(String value) {
            addCriterion("MANAGER_PERSON not like", value, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonIn(List<String> values) {
            addCriterion("MANAGER_PERSON in", values, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonNotIn(List<String> values) {
            addCriterion("MANAGER_PERSON not in", values, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonBetween(String value1, String value2) {
            addCriterion("MANAGER_PERSON between", value1, value2, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andManagerPersonNotBetween(String value1, String value2) {
            addCriterion("MANAGER_PERSON not between", value1, value2, "managerPerson");
            return (Criteria) this;
        }

        public Criteria andCreateStaffIsNull() {
            addCriterion("CREATE_STAFF is null");
            return (Criteria) this;
        }

        public Criteria andCreateStaffIsNotNull() {
            addCriterion("CREATE_STAFF is not null");
            return (Criteria) this;
        }

        public Criteria andCreateStaffEqualTo(String value) {
            addCriterion("CREATE_STAFF =", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffNotEqualTo(String value) {
            addCriterion("CREATE_STAFF <>", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffGreaterThan(String value) {
            addCriterion("CREATE_STAFF >", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_STAFF >=", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffLessThan(String value) {
            addCriterion("CREATE_STAFF <", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffLessThanOrEqualTo(String value) {
            addCriterion("CREATE_STAFF <=", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffLike(String value) {
            addCriterion("CREATE_STAFF like", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffNotLike(String value) {
            addCriterion("CREATE_STAFF not like", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffIn(List<String> values) {
            addCriterion("CREATE_STAFF in", values, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffNotIn(List<String> values) {
            addCriterion("CREATE_STAFF not in", values, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffBetween(String value1, String value2) {
            addCriterion("CREATE_STAFF between", value1, value2, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffNotBetween(String value1, String value2) {
            addCriterion("CREATE_STAFF not between", value1, value2, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIsNull() {
            addCriterion("UPDATE_STAFF is null");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIsNotNull() {
            addCriterion("UPDATE_STAFF is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffEqualTo(String value) {
            addCriterion("UPDATE_STAFF =", value, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffNotEqualTo(String value) {
            addCriterion("UPDATE_STAFF <>", value, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffGreaterThan(String value) {
            addCriterion("UPDATE_STAFF >", value, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_STAFF >=", value, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffLessThan(String value) {
            addCriterion("UPDATE_STAFF <", value, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_STAFF <=", value, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffLike(String value) {
            addCriterion("UPDATE_STAFF like", value, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffNotLike(String value) {
            addCriterion("UPDATE_STAFF not like", value, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIn(List<String> values) {
            addCriterion("UPDATE_STAFF in", values, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffNotIn(List<String> values) {
            addCriterion("UPDATE_STAFF not in", values, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffBetween(String value1, String value2) {
            addCriterion("UPDATE_STAFF between", value1, value2, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffNotBetween(String value1, String value2) {
            addCriterion("UPDATE_STAFF not between", value1, value2, "updateStaff");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Timestamp value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Timestamp value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Timestamp> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Timestamp> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_origin_merchant_stock_out
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}