package com.bdx.rainbow.spsy.dal.ibatis.model;

public class TOriginSkuAgencyRelationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_origin_sku_agency_relation.SKU_ID
     *
     * @mbggenerated
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_origin_sku_agency_relation.AGENCY_ID
     *
     * @mbggenerated
     */
    private Integer agencyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_origin_sku_agency_relation.SKU_ID
     *
     * @return the value of t_origin_sku_agency_relation.SKU_ID
     *
     * @mbggenerated
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_origin_sku_agency_relation.SKU_ID
     *
     * @param skuId the value for t_origin_sku_agency_relation.SKU_ID
     *
     * @mbggenerated
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_origin_sku_agency_relation.AGENCY_ID
     *
     * @return the value of t_origin_sku_agency_relation.AGENCY_ID
     *
     * @mbggenerated
     */
    public Integer getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_origin_sku_agency_relation.AGENCY_ID
     *
     * @param agencyId the value for t_origin_sku_agency_relation.AGENCY_ID
     *
     * @mbggenerated
     */
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }
}