package com.bdx.rainbow.entity.jc;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class JcSkuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    protected String suffix = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    protected int limitClauseStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    protected int limitClauseCount = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public JcSkuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public void setLimitClauseStart(int limitClauseStart) {
        this.limitClauseStart=limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public int getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public void setLimitClauseCount(int limitClauseCount) {
        this.limitClauseCount=limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public int getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSkuBarcodeIsNull() {
            addCriterion("SKU_BARCODE is null");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeIsNotNull() {
            addCriterion("SKU_BARCODE is not null");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeEqualTo(String value) {
            addCriterion("SKU_BARCODE =", value, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeNotEqualTo(String value) {
            addCriterion("SKU_BARCODE <>", value, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeGreaterThan(String value) {
            addCriterion("SKU_BARCODE >", value, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_BARCODE >=", value, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeLessThan(String value) {
            addCriterion("SKU_BARCODE <", value, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeLessThanOrEqualTo(String value) {
            addCriterion("SKU_BARCODE <=", value, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeLike(String value) {
            addCriterion("SKU_BARCODE like", value, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeNotLike(String value) {
            addCriterion("SKU_BARCODE not like", value, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeIn(List<String> values) {
            addCriterion("SKU_BARCODE in", values, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeNotIn(List<String> values) {
            addCriterion("SKU_BARCODE not in", values, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeBetween(String value1, String value2) {
            addCriterion("SKU_BARCODE between", value1, value2, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuBarcodeNotBetween(String value1, String value2) {
            addCriterion("SKU_BARCODE not between", value1, value2, "skuBarcode");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("SKU_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("SKU_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(String value) {
            addCriterion("SKU_NAME =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(String value) {
            addCriterion("SKU_NAME <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(String value) {
            addCriterion("SKU_NAME >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_NAME >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(String value) {
            addCriterion("SKU_NAME <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(String value) {
            addCriterion("SKU_NAME <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLike(String value) {
            addCriterion("SKU_NAME like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotLike(String value) {
            addCriterion("SKU_NAME not like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<String> values) {
            addCriterion("SKU_NAME in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<String> values) {
            addCriterion("SKU_NAME not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(String value1, String value2) {
            addCriterion("SKU_NAME between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(String value1, String value2) {
            addCriterion("SKU_NAME not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineIsNull() {
            addCriterion("SAFE_DEADLINE is null");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineIsNotNull() {
            addCriterion("SAFE_DEADLINE is not null");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineEqualTo(String value) {
            addCriterion("SAFE_DEADLINE =", value, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineNotEqualTo(String value) {
            addCriterion("SAFE_DEADLINE <>", value, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineGreaterThan(String value) {
            addCriterion("SAFE_DEADLINE >", value, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineGreaterThanOrEqualTo(String value) {
            addCriterion("SAFE_DEADLINE >=", value, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineLessThan(String value) {
            addCriterion("SAFE_DEADLINE <", value, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineLessThanOrEqualTo(String value) {
            addCriterion("SAFE_DEADLINE <=", value, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineLike(String value) {
            addCriterion("SAFE_DEADLINE like", value, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineNotLike(String value) {
            addCriterion("SAFE_DEADLINE not like", value, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineIn(List<String> values) {
            addCriterion("SAFE_DEADLINE in", values, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineNotIn(List<String> values) {
            addCriterion("SAFE_DEADLINE not in", values, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineBetween(String value1, String value2) {
            addCriterion("SAFE_DEADLINE between", value1, value2, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineNotBetween(String value1, String value2) {
            addCriterion("SAFE_DEADLINE not between", value1, value2, "safeDeadline");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("UNIT is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("UNIT =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("UNIT <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("UNIT >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("UNIT <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("UNIT <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("UNIT like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("UNIT not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("UNIT in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("UNIT not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("UNIT between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("UNIT not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andSkuType1IsNull() {
            addCriterion("SKU_TYPE1 is null");
            return (Criteria) this;
        }

        public Criteria andSkuType1IsNotNull() {
            addCriterion("SKU_TYPE1 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuType1EqualTo(String value) {
            addCriterion("SKU_TYPE1 =", value, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1NotEqualTo(String value) {
            addCriterion("SKU_TYPE1 <>", value, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1GreaterThan(String value) {
            addCriterion("SKU_TYPE1 >", value, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1GreaterThanOrEqualTo(String value) {
            addCriterion("SKU_TYPE1 >=", value, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1LessThan(String value) {
            addCriterion("SKU_TYPE1 <", value, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1LessThanOrEqualTo(String value) {
            addCriterion("SKU_TYPE1 <=", value, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1Like(String value) {
            addCriterion("SKU_TYPE1 like", value, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1NotLike(String value) {
            addCriterion("SKU_TYPE1 not like", value, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1In(List<String> values) {
            addCriterion("SKU_TYPE1 in", values, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1NotIn(List<String> values) {
            addCriterion("SKU_TYPE1 not in", values, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1Between(String value1, String value2) {
            addCriterion("SKU_TYPE1 between", value1, value2, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType1NotBetween(String value1, String value2) {
            addCriterion("SKU_TYPE1 not between", value1, value2, "skuType1");
            return (Criteria) this;
        }

        public Criteria andSkuType2IsNull() {
            addCriterion("SKU_TYPE2 is null");
            return (Criteria) this;
        }

        public Criteria andSkuType2IsNotNull() {
            addCriterion("SKU_TYPE2 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuType2EqualTo(String value) {
            addCriterion("SKU_TYPE2 =", value, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2NotEqualTo(String value) {
            addCriterion("SKU_TYPE2 <>", value, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2GreaterThan(String value) {
            addCriterion("SKU_TYPE2 >", value, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2GreaterThanOrEqualTo(String value) {
            addCriterion("SKU_TYPE2 >=", value, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2LessThan(String value) {
            addCriterion("SKU_TYPE2 <", value, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2LessThanOrEqualTo(String value) {
            addCriterion("SKU_TYPE2 <=", value, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2Like(String value) {
            addCriterion("SKU_TYPE2 like", value, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2NotLike(String value) {
            addCriterion("SKU_TYPE2 not like", value, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2In(List<String> values) {
            addCriterion("SKU_TYPE2 in", values, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2NotIn(List<String> values) {
            addCriterion("SKU_TYPE2 not in", values, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2Between(String value1, String value2) {
            addCriterion("SKU_TYPE2 between", value1, value2, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuType2NotBetween(String value1, String value2) {
            addCriterion("SKU_TYPE2 not between", value1, value2, "skuType2");
            return (Criteria) this;
        }

        public Criteria andSkuBrandIsNull() {
            addCriterion("SKU_BRAND is null");
            return (Criteria) this;
        }

        public Criteria andSkuBrandIsNotNull() {
            addCriterion("SKU_BRAND is not null");
            return (Criteria) this;
        }

        public Criteria andSkuBrandEqualTo(String value) {
            addCriterion("SKU_BRAND =", value, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandNotEqualTo(String value) {
            addCriterion("SKU_BRAND <>", value, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandGreaterThan(String value) {
            addCriterion("SKU_BRAND >", value, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_BRAND >=", value, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandLessThan(String value) {
            addCriterion("SKU_BRAND <", value, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandLessThanOrEqualTo(String value) {
            addCriterion("SKU_BRAND <=", value, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandLike(String value) {
            addCriterion("SKU_BRAND like", value, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandNotLike(String value) {
            addCriterion("SKU_BRAND not like", value, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandIn(List<String> values) {
            addCriterion("SKU_BRAND in", values, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandNotIn(List<String> values) {
            addCriterion("SKU_BRAND not in", values, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandBetween(String value1, String value2) {
            addCriterion("SKU_BRAND between", value1, value2, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuBrandNotBetween(String value1, String value2) {
            addCriterion("SKU_BRAND not between", value1, value2, "skuBrand");
            return (Criteria) this;
        }

        public Criteria andSkuSpecIsNull() {
            addCriterion("SKU_SPEC is null");
            return (Criteria) this;
        }

        public Criteria andSkuSpecIsNotNull() {
            addCriterion("SKU_SPEC is not null");
            return (Criteria) this;
        }

        public Criteria andSkuSpecEqualTo(String value) {
            addCriterion("SKU_SPEC =", value, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecNotEqualTo(String value) {
            addCriterion("SKU_SPEC <>", value, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecGreaterThan(String value) {
            addCriterion("SKU_SPEC >", value, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_SPEC >=", value, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecLessThan(String value) {
            addCriterion("SKU_SPEC <", value, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecLessThanOrEqualTo(String value) {
            addCriterion("SKU_SPEC <=", value, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecLike(String value) {
            addCriterion("SKU_SPEC like", value, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecNotLike(String value) {
            addCriterion("SKU_SPEC not like", value, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecIn(List<String> values) {
            addCriterion("SKU_SPEC in", values, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecNotIn(List<String> values) {
            addCriterion("SKU_SPEC not in", values, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecBetween(String value1, String value2) {
            addCriterion("SKU_SPEC between", value1, value2, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andSkuSpecNotBetween(String value1, String value2) {
            addCriterion("SKU_SPEC not between", value1, value2, "skuSpec");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeIsNull() {
            addCriterion("CREATE_EMP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeIsNotNull() {
            addCriterion("CREATE_EMP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeEqualTo(String value) {
            addCriterion("CREATE_EMP_CODE =", value, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeNotEqualTo(String value) {
            addCriterion("CREATE_EMP_CODE <>", value, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeGreaterThan(String value) {
            addCriterion("CREATE_EMP_CODE >", value, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_EMP_CODE >=", value, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeLessThan(String value) {
            addCriterion("CREATE_EMP_CODE <", value, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_EMP_CODE <=", value, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeLike(String value) {
            addCriterion("CREATE_EMP_CODE like", value, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeNotLike(String value) {
            addCriterion("CREATE_EMP_CODE not like", value, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeIn(List<String> values) {
            addCriterion("CREATE_EMP_CODE in", values, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeNotIn(List<String> values) {
            addCriterion("CREATE_EMP_CODE not in", values, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeBetween(String value1, String value2) {
            addCriterion("CREATE_EMP_CODE between", value1, value2, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andCreateEmpCodeNotBetween(String value1, String value2) {
            addCriterion("CREATE_EMP_CODE not between", value1, value2, "createEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Timestamp value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Timestamp value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Timestamp> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Timestamp> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeIsNull() {
            addCriterion("UPDATE_EMP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeIsNotNull() {
            addCriterion("UPDATE_EMP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeEqualTo(String value) {
            addCriterion("UPDATE_EMP_CODE =", value, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeNotEqualTo(String value) {
            addCriterion("UPDATE_EMP_CODE <>", value, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeGreaterThan(String value) {
            addCriterion("UPDATE_EMP_CODE >", value, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_EMP_CODE >=", value, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeLessThan(String value) {
            addCriterion("UPDATE_EMP_CODE <", value, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_EMP_CODE <=", value, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeLike(String value) {
            addCriterion("UPDATE_EMP_CODE like", value, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeNotLike(String value) {
            addCriterion("UPDATE_EMP_CODE not like", value, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeIn(List<String> values) {
            addCriterion("UPDATE_EMP_CODE in", values, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeNotIn(List<String> values) {
            addCriterion("UPDATE_EMP_CODE not in", values, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeBetween(String value1, String value2) {
            addCriterion("UPDATE_EMP_CODE between", value1, value2, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpCodeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_EMP_CODE not between", value1, value2, "updateEmpCode");
            return (Criteria) this;
        }

        public Criteria andStatNumIsNull() {
            addCriterion("STAT_NUM is null");
            return (Criteria) this;
        }

        public Criteria andStatNumIsNotNull() {
            addCriterion("STAT_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andStatNumEqualTo(BigDecimal value) {
            addCriterion("STAT_NUM =", value, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumNotEqualTo(BigDecimal value) {
            addCriterion("STAT_NUM <>", value, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumGreaterThan(BigDecimal value) {
            addCriterion("STAT_NUM >", value, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STAT_NUM >=", value, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumLessThan(BigDecimal value) {
            addCriterion("STAT_NUM <", value, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STAT_NUM <=", value, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumIn(List<BigDecimal> values) {
            addCriterion("STAT_NUM in", values, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumNotIn(List<BigDecimal> values) {
            addCriterion("STAT_NUM not in", values, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STAT_NUM between", value1, value2, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STAT_NUM not between", value1, value2, "statNum");
            return (Criteria) this;
        }

        public Criteria andStatUnitIsNull() {
            addCriterion("STAT_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andStatUnitIsNotNull() {
            addCriterion("STAT_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andStatUnitEqualTo(String value) {
            addCriterion("STAT_UNIT =", value, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitNotEqualTo(String value) {
            addCriterion("STAT_UNIT <>", value, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitGreaterThan(String value) {
            addCriterion("STAT_UNIT >", value, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitGreaterThanOrEqualTo(String value) {
            addCriterion("STAT_UNIT >=", value, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitLessThan(String value) {
            addCriterion("STAT_UNIT <", value, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitLessThanOrEqualTo(String value) {
            addCriterion("STAT_UNIT <=", value, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitLike(String value) {
            addCriterion("STAT_UNIT like", value, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitNotLike(String value) {
            addCriterion("STAT_UNIT not like", value, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitIn(List<String> values) {
            addCriterion("STAT_UNIT in", values, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitNotIn(List<String> values) {
            addCriterion("STAT_UNIT not in", values, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitBetween(String value1, String value2) {
            addCriterion("STAT_UNIT between", value1, value2, "statUnit");
            return (Criteria) this;
        }

        public Criteria andStatUnitNotBetween(String value1, String value2) {
            addCriterion("STAT_UNIT not between", value1, value2, "statUnit");
            return (Criteria) this;
        }

        public Criteria andSkuType3IsNull() {
            addCriterion("SKU_TYPE3 is null");
            return (Criteria) this;
        }

        public Criteria andSkuType3IsNotNull() {
            addCriterion("SKU_TYPE3 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuType3EqualTo(String value) {
            addCriterion("SKU_TYPE3 =", value, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3NotEqualTo(String value) {
            addCriterion("SKU_TYPE3 <>", value, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3GreaterThan(String value) {
            addCriterion("SKU_TYPE3 >", value, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3GreaterThanOrEqualTo(String value) {
            addCriterion("SKU_TYPE3 >=", value, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3LessThan(String value) {
            addCriterion("SKU_TYPE3 <", value, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3LessThanOrEqualTo(String value) {
            addCriterion("SKU_TYPE3 <=", value, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3Like(String value) {
            addCriterion("SKU_TYPE3 like", value, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3NotLike(String value) {
            addCriterion("SKU_TYPE3 not like", value, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3In(List<String> values) {
            addCriterion("SKU_TYPE3 in", values, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3NotIn(List<String> values) {
            addCriterion("SKU_TYPE3 not in", values, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3Between(String value1, String value2) {
            addCriterion("SKU_TYPE3 between", value1, value2, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSkuType3NotBetween(String value1, String value2) {
            addCriterion("SKU_TYPE3 not between", value1, value2, "skuType3");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitIsNull() {
            addCriterion("SAFE_DEADLINE_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitIsNotNull() {
            addCriterion("SAFE_DEADLINE_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitEqualTo(String value) {
            addCriterion("SAFE_DEADLINE_UNIT =", value, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitNotEqualTo(String value) {
            addCriterion("SAFE_DEADLINE_UNIT <>", value, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitGreaterThan(String value) {
            addCriterion("SAFE_DEADLINE_UNIT >", value, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitGreaterThanOrEqualTo(String value) {
            addCriterion("SAFE_DEADLINE_UNIT >=", value, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitLessThan(String value) {
            addCriterion("SAFE_DEADLINE_UNIT <", value, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitLessThanOrEqualTo(String value) {
            addCriterion("SAFE_DEADLINE_UNIT <=", value, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitLike(String value) {
            addCriterion("SAFE_DEADLINE_UNIT like", value, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitNotLike(String value) {
            addCriterion("SAFE_DEADLINE_UNIT not like", value, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitIn(List<String> values) {
            addCriterion("SAFE_DEADLINE_UNIT in", values, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitNotIn(List<String> values) {
            addCriterion("SAFE_DEADLINE_UNIT not in", values, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitBetween(String value1, String value2) {
            addCriterion("SAFE_DEADLINE_UNIT between", value1, value2, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andSafeDeadlineUnitNotBetween(String value1, String value2) {
            addCriterion("SAFE_DEADLINE_UNIT not between", value1, value2, "safeDeadlineUnit");
            return (Criteria) this;
        }

        public Criteria andIcoIsNull() {
            addCriterion("ICO is null");
            return (Criteria) this;
        }

        public Criteria andIcoIsNotNull() {
            addCriterion("ICO is not null");
            return (Criteria) this;
        }

        public Criteria andIcoEqualTo(String value) {
            addCriterion("ICO =", value, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoNotEqualTo(String value) {
            addCriterion("ICO <>", value, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoGreaterThan(String value) {
            addCriterion("ICO >", value, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoGreaterThanOrEqualTo(String value) {
            addCriterion("ICO >=", value, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoLessThan(String value) {
            addCriterion("ICO <", value, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoLessThanOrEqualTo(String value) {
            addCriterion("ICO <=", value, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoLike(String value) {
            addCriterion("ICO like", value, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoNotLike(String value) {
            addCriterion("ICO not like", value, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoIn(List<String> values) {
            addCriterion("ICO in", values, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoNotIn(List<String> values) {
            addCriterion("ICO not in", values, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoBetween(String value1, String value2) {
            addCriterion("ICO between", value1, value2, "ico");
            return (Criteria) this;
        }

        public Criteria andIcoNotBetween(String value1, String value2) {
            addCriterion("ICO not between", value1, value2, "ico");
            return (Criteria) this;
        }

        public Criteria andTempIsNull() {
            addCriterion("TEMP is null");
            return (Criteria) this;
        }

        public Criteria andTempIsNotNull() {
            addCriterion("TEMP is not null");
            return (Criteria) this;
        }

        public Criteria andTempEqualTo(Long value) {
            addCriterion("TEMP =", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotEqualTo(Long value) {
            addCriterion("TEMP <>", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempGreaterThan(Long value) {
            addCriterion("TEMP >", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempGreaterThanOrEqualTo(Long value) {
            addCriterion("TEMP >=", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLessThan(Long value) {
            addCriterion("TEMP <", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLessThanOrEqualTo(Long value) {
            addCriterion("TEMP <=", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempIn(List<Long> values) {
            addCriterion("TEMP in", values, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotIn(List<Long> values) {
            addCriterion("TEMP not in", values, "temp");
            return (Criteria) this;
        }

        public Criteria andTempBetween(Long value1, Long value2) {
            addCriterion("TEMP between", value1, value2, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotBetween(Long value1, Long value2) {
            addCriterion("TEMP not between", value1, value2, "temp");
            return (Criteria) this;
        }

        public Criteria andImgsIsNull() {
            addCriterion("IMGS is null");
            return (Criteria) this;
        }

        public Criteria andImgsIsNotNull() {
            addCriterion("IMGS is not null");
            return (Criteria) this;
        }

        public Criteria andImgsEqualTo(String value) {
            addCriterion("IMGS =", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotEqualTo(String value) {
            addCriterion("IMGS <>", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsGreaterThan(String value) {
            addCriterion("IMGS >", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsGreaterThanOrEqualTo(String value) {
            addCriterion("IMGS >=", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLessThan(String value) {
            addCriterion("IMGS <", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLessThanOrEqualTo(String value) {
            addCriterion("IMGS <=", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLike(String value) {
            addCriterion("IMGS like", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotLike(String value) {
            addCriterion("IMGS not like", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsIn(List<String> values) {
            addCriterion("IMGS in", values, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotIn(List<String> values) {
            addCriterion("IMGS not in", values, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsBetween(String value1, String value2) {
            addCriterion("IMGS between", value1, value2, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotBetween(String value1, String value2) {
            addCriterion("IMGS not between", value1, value2, "imgs");
            return (Criteria) this;
        }

        public Criteria andPNameIsNull() {
            addCriterion("P_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPNameIsNotNull() {
            addCriterion("P_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPNameEqualTo(String value) {
            addCriterion("P_NAME =", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotEqualTo(String value) {
            addCriterion("P_NAME <>", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThan(String value) {
            addCriterion("P_NAME >", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThanOrEqualTo(String value) {
            addCriterion("P_NAME >=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThan(String value) {
            addCriterion("P_NAME <", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThanOrEqualTo(String value) {
            addCriterion("P_NAME <=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLike(String value) {
            addCriterion("P_NAME like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotLike(String value) {
            addCriterion("P_NAME not like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameIn(List<String> values) {
            addCriterion("P_NAME in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotIn(List<String> values) {
            addCriterion("P_NAME not in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameBetween(String value1, String value2) {
            addCriterion("P_NAME between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotBetween(String value1, String value2) {
            addCriterion("P_NAME not between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPAddressIsNull() {
            addCriterion("P_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andPAddressIsNotNull() {
            addCriterion("P_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andPAddressEqualTo(String value) {
            addCriterion("P_ADDRESS =", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressNotEqualTo(String value) {
            addCriterion("P_ADDRESS <>", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressGreaterThan(String value) {
            addCriterion("P_ADDRESS >", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressGreaterThanOrEqualTo(String value) {
            addCriterion("P_ADDRESS >=", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressLessThan(String value) {
            addCriterion("P_ADDRESS <", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressLessThanOrEqualTo(String value) {
            addCriterion("P_ADDRESS <=", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressLike(String value) {
            addCriterion("P_ADDRESS like", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressNotLike(String value) {
            addCriterion("P_ADDRESS not like", value, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressIn(List<String> values) {
            addCriterion("P_ADDRESS in", values, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressNotIn(List<String> values) {
            addCriterion("P_ADDRESS not in", values, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressBetween(String value1, String value2) {
            addCriterion("P_ADDRESS between", value1, value2, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAddressNotBetween(String value1, String value2) {
            addCriterion("P_ADDRESS not between", value1, value2, "pAddress");
            return (Criteria) this;
        }

        public Criteria andPAreaIsNull() {
            addCriterion("P_AREA is null");
            return (Criteria) this;
        }

        public Criteria andPAreaIsNotNull() {
            addCriterion("P_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andPAreaEqualTo(String value) {
            addCriterion("P_AREA =", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaNotEqualTo(String value) {
            addCriterion("P_AREA <>", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaGreaterThan(String value) {
            addCriterion("P_AREA >", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaGreaterThanOrEqualTo(String value) {
            addCriterion("P_AREA >=", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaLessThan(String value) {
            addCriterion("P_AREA <", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaLessThanOrEqualTo(String value) {
            addCriterion("P_AREA <=", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaLike(String value) {
            addCriterion("P_AREA like", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaNotLike(String value) {
            addCriterion("P_AREA not like", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaIn(List<String> values) {
            addCriterion("P_AREA in", values, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaNotIn(List<String> values) {
            addCriterion("P_AREA not in", values, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaBetween(String value1, String value2) {
            addCriterion("P_AREA between", value1, value2, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaNotBetween(String value1, String value2) {
            addCriterion("P_AREA not between", value1, value2, "pArea");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPCodeIsNull() {
            addCriterion("P_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPCodeIsNotNull() {
            addCriterion("P_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPCodeEqualTo(String value) {
            addCriterion("P_CODE =", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotEqualTo(String value) {
            addCriterion("P_CODE <>", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeGreaterThan(String value) {
            addCriterion("P_CODE >", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeGreaterThanOrEqualTo(String value) {
            addCriterion("P_CODE >=", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLessThan(String value) {
            addCriterion("P_CODE <", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLessThanOrEqualTo(String value) {
            addCriterion("P_CODE <=", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLike(String value) {
            addCriterion("P_CODE like", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotLike(String value) {
            addCriterion("P_CODE not like", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeIn(List<String> values) {
            addCriterion("P_CODE in", values, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotIn(List<String> values) {
            addCriterion("P_CODE not in", values, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeBetween(String value1, String value2) {
            addCriterion("P_CODE between", value1, value2, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotBetween(String value1, String value2) {
            addCriterion("P_CODE not between", value1, value2, "pCode");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeIsNull() {
            addCriterion("ORGI_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeIsNotNull() {
            addCriterion("ORGI_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeEqualTo(String value) {
            addCriterion("ORGI_TYPE =", value, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeNotEqualTo(String value) {
            addCriterion("ORGI_TYPE <>", value, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeGreaterThan(String value) {
            addCriterion("ORGI_TYPE >", value, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ORGI_TYPE >=", value, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeLessThan(String value) {
            addCriterion("ORGI_TYPE <", value, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeLessThanOrEqualTo(String value) {
            addCriterion("ORGI_TYPE <=", value, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeLike(String value) {
            addCriterion("ORGI_TYPE like", value, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeNotLike(String value) {
            addCriterion("ORGI_TYPE not like", value, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeIn(List<String> values) {
            addCriterion("ORGI_TYPE in", values, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeNotIn(List<String> values) {
            addCriterion("ORGI_TYPE not in", values, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeBetween(String value1, String value2) {
            addCriterion("ORGI_TYPE between", value1, value2, "orgiType");
            return (Criteria) this;
        }

        public Criteria andOrgiTypeNotBetween(String value1, String value2) {
            addCriterion("ORGI_TYPE not between", value1, value2, "orgiType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeIsNull() {
            addCriterion("GDS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andGdsTypeIsNotNull() {
            addCriterion("GDS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andGdsTypeEqualTo(String value) {
            addCriterion("GDS_TYPE =", value, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeNotEqualTo(String value) {
            addCriterion("GDS_TYPE <>", value, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeGreaterThan(String value) {
            addCriterion("GDS_TYPE >", value, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("GDS_TYPE >=", value, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeLessThan(String value) {
            addCriterion("GDS_TYPE <", value, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeLessThanOrEqualTo(String value) {
            addCriterion("GDS_TYPE <=", value, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeLike(String value) {
            addCriterion("GDS_TYPE like", value, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeNotLike(String value) {
            addCriterion("GDS_TYPE not like", value, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeIn(List<String> values) {
            addCriterion("GDS_TYPE in", values, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeNotIn(List<String> values) {
            addCriterion("GDS_TYPE not in", values, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeBetween(String value1, String value2) {
            addCriterion("GDS_TYPE between", value1, value2, "gdsType");
            return (Criteria) this;
        }

        public Criteria andGdsTypeNotBetween(String value1, String value2) {
            addCriterion("GDS_TYPE not between", value1, value2, "gdsType");
            return (Criteria) this;
        }

        public Criteria andChangeNoteIsNull() {
            addCriterion("CHANGE_NOTE is null");
            return (Criteria) this;
        }

        public Criteria andChangeNoteIsNotNull() {
            addCriterion("CHANGE_NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andChangeNoteEqualTo(String value) {
            addCriterion("CHANGE_NOTE =", value, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteNotEqualTo(String value) {
            addCriterion("CHANGE_NOTE <>", value, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteGreaterThan(String value) {
            addCriterion("CHANGE_NOTE >", value, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteGreaterThanOrEqualTo(String value) {
            addCriterion("CHANGE_NOTE >=", value, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteLessThan(String value) {
            addCriterion("CHANGE_NOTE <", value, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteLessThanOrEqualTo(String value) {
            addCriterion("CHANGE_NOTE <=", value, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteLike(String value) {
            addCriterion("CHANGE_NOTE like", value, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteNotLike(String value) {
            addCriterion("CHANGE_NOTE not like", value, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteIn(List<String> values) {
            addCriterion("CHANGE_NOTE in", values, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteNotIn(List<String> values) {
            addCriterion("CHANGE_NOTE not in", values, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteBetween(String value1, String value2) {
            addCriterion("CHANGE_NOTE between", value1, value2, "changeNote");
            return (Criteria) this;
        }

        public Criteria andChangeNoteNotBetween(String value1, String value2) {
            addCriterion("CHANGE_NOTE not between", value1, value2, "changeNote");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("SKU_ID is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("SKU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Long value) {
            addCriterion("SKU_ID =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Long value) {
            addCriterion("SKU_ID <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Long value) {
            addCriterion("SKU_ID >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SKU_ID >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Long value) {
            addCriterion("SKU_ID <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Long value) {
            addCriterion("SKU_ID <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Long> values) {
            addCriterion("SKU_ID in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Long> values) {
            addCriterion("SKU_ID not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Long value1, Long value2) {
            addCriterion("SKU_ID between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Long value1, Long value2) {
            addCriterion("SKU_ID not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("AUDIT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("AUDIT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Timestamp value) {
            addCriterion("AUDIT_TIME =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Timestamp value) {
            addCriterion("AUDIT_TIME <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Timestamp value) {
            addCriterion("AUDIT_TIME >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("AUDIT_TIME >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Timestamp value) {
            addCriterion("AUDIT_TIME <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("AUDIT_TIME <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Timestamp> values) {
            addCriterion("AUDIT_TIME in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Timestamp> values) {
            addCriterion("AUDIT_TIME not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("AUDIT_TIME between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("AUDIT_TIME not between", value1, value2, "auditTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_sku
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 18 14:56:54 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_sku
     *
     * @mbggenerated Mon Jan 18 14:56:54 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}