package com.bdx.rainbow.mapp.model.bean;

import java.sql.Timestamp;

import com.bdx.rainbow.mapp.model.BDXBody;

public class TYdzfMonitorTempletContentMB extends  BDXBody{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.MONITOR_TEMPLET_CONTENT_ID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private Integer monitorTempletContentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.MONITOR_TEMPLET_ID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private Integer monitorTempletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.ITEM_CONTENT
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private String itemContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.ITEM_VALUE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private Integer itemValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.ITEM_REMARK
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private String itemRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.IS_DEL
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.CREATE_DATE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private Timestamp createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.CREATE_USERID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private Integer createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private Timestamp updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet_content.UPDATE_USERID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    private Integer updateUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.MONITOR_TEMPLET_CONTENT_ID
     *
     * @return the value of t_ydzf_monitor_templet_content.MONITOR_TEMPLET_CONTENT_ID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public Integer getMonitorTempletContentId() {
        return monitorTempletContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.MONITOR_TEMPLET_CONTENT_ID
     *
     * @param monitorTempletContentId the value for t_ydzf_monitor_templet_content.MONITOR_TEMPLET_CONTENT_ID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setMonitorTempletContentId(Integer monitorTempletContentId) {
        this.monitorTempletContentId = monitorTempletContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.MONITOR_TEMPLET_ID
     *
     * @return the value of t_ydzf_monitor_templet_content.MONITOR_TEMPLET_ID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public Integer getMonitorTempletId() {
        return monitorTempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.MONITOR_TEMPLET_ID
     *
     * @param monitorTempletId the value for t_ydzf_monitor_templet_content.MONITOR_TEMPLET_ID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setMonitorTempletId(Integer monitorTempletId) {
        this.monitorTempletId = monitorTempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.ITEM_CONTENT
     *
     * @return the value of t_ydzf_monitor_templet_content.ITEM_CONTENT
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public String getItemContent() {
        return itemContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.ITEM_CONTENT
     *
     * @param itemContent the value for t_ydzf_monitor_templet_content.ITEM_CONTENT
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setItemContent(String itemContent) {
        this.itemContent = itemContent == null ? null : itemContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.ITEM_VALUE
     *
     * @return the value of t_ydzf_monitor_templet_content.ITEM_VALUE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public Integer getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.ITEM_VALUE
     *
     * @param itemValue the value for t_ydzf_monitor_templet_content.ITEM_VALUE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setItemValue(Integer itemValue) {
        this.itemValue = itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.ITEM_REMARK
     *
     * @return the value of t_ydzf_monitor_templet_content.ITEM_REMARK
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public String getItemRemark() {
        return itemRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.ITEM_REMARK
     *
     * @param itemRemark the value for t_ydzf_monitor_templet_content.ITEM_REMARK
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setItemRemark(String itemRemark) {
        this.itemRemark = itemRemark == null ? null : itemRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.IS_DEL
     *
     * @return the value of t_ydzf_monitor_templet_content.IS_DEL
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.IS_DEL
     *
     * @param isDel the value for t_ydzf_monitor_templet_content.IS_DEL
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.CREATE_DATE
     *
     * @return the value of t_ydzf_monitor_templet_content.CREATE_DATE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public Timestamp getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.CREATE_DATE
     *
     * @param createDate the value for t_ydzf_monitor_templet_content.CREATE_DATE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.CREATE_USERID
     *
     * @return the value of t_ydzf_monitor_templet_content.CREATE_USERID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public Integer getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.CREATE_USERID
     *
     * @param createUserid the value for t_ydzf_monitor_templet_content.CREATE_USERID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setCreateUserid(Integer createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.UPDATE_DATE
     *
     * @return the value of t_ydzf_monitor_templet_content.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public Timestamp getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.UPDATE_DATE
     *
     * @param updateDate the value for t_ydzf_monitor_templet_content.UPDATE_DATE
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet_content.UPDATE_USERID
     *
     * @return the value of t_ydzf_monitor_templet_content.UPDATE_USERID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet_content.UPDATE_USERID
     *
     * @param updateUserid the value for t_ydzf_monitor_templet_content.UPDATE_USERID
     *
     * @mbggenerated Thu Mar 31 00:22:44 GMT+08:00 2016
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

}