package com.bdx.rainbow.mapp.model.bean;

import java.sql.Timestamp;

import com.bdx.rainbow.mapp.model.BDXBody;

public class TYdzfMonitorTempletMB extends  BDXBody{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_ID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private Integer monitorTempletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_NAME
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private String monitorTempletName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_CONTENT
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private String monitorTempletContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.CHECK_ENTERPRISE_TYPE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private String checkEnterpriseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.CHECK_PLAN_TYPE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private String checkPlanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.PASS_VALUE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private Integer passValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.IS_DEL
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.CREATE_DATE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private Timestamp createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.CREATE_USERID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private Integer createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private Timestamp updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_monitor_templet.UPDATE_USERID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    private Integer updateUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_ID
     *
     * @return the value of t_ydzf_monitor_templet.MONITOR_TEMPLET_ID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public Integer getMonitorTempletId() {
        return monitorTempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_ID
     *
     * @param monitorTempletId the value for t_ydzf_monitor_templet.MONITOR_TEMPLET_ID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setMonitorTempletId(Integer monitorTempletId) {
        this.monitorTempletId = monitorTempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_NAME
     *
     * @return the value of t_ydzf_monitor_templet.MONITOR_TEMPLET_NAME
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public String getMonitorTempletName() {
        return monitorTempletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_NAME
     *
     * @param monitorTempletName the value for t_ydzf_monitor_templet.MONITOR_TEMPLET_NAME
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setMonitorTempletName(String monitorTempletName) {
        this.monitorTempletName = monitorTempletName == null ? null : monitorTempletName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_CONTENT
     *
     * @return the value of t_ydzf_monitor_templet.MONITOR_TEMPLET_CONTENT
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public String getMonitorTempletContent() {
        return monitorTempletContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.MONITOR_TEMPLET_CONTENT
     *
     * @param monitorTempletContent the value for t_ydzf_monitor_templet.MONITOR_TEMPLET_CONTENT
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setMonitorTempletContent(String monitorTempletContent) {
        this.monitorTempletContent = monitorTempletContent == null ? null : monitorTempletContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.CHECK_ENTERPRISE_TYPE
     *
     * @return the value of t_ydzf_monitor_templet.CHECK_ENTERPRISE_TYPE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public String getCheckEnterpriseType() {
        return checkEnterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.CHECK_ENTERPRISE_TYPE
     *
     * @param checkEnterpriseType the value for t_ydzf_monitor_templet.CHECK_ENTERPRISE_TYPE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setCheckEnterpriseType(String checkEnterpriseType) {
        this.checkEnterpriseType = checkEnterpriseType == null ? null : checkEnterpriseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.CHECK_PLAN_TYPE
     *
     * @return the value of t_ydzf_monitor_templet.CHECK_PLAN_TYPE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public String getCheckPlanType() {
        return checkPlanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.CHECK_PLAN_TYPE
     *
     * @param checkPlanType the value for t_ydzf_monitor_templet.CHECK_PLAN_TYPE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setCheckPlanType(String checkPlanType) {
        this.checkPlanType = checkPlanType == null ? null : checkPlanType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.PASS_VALUE
     *
     * @return the value of t_ydzf_monitor_templet.PASS_VALUE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public Integer getPassValue() {
        return passValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.PASS_VALUE
     *
     * @param passValue the value for t_ydzf_monitor_templet.PASS_VALUE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setPassValue(Integer passValue) {
        this.passValue = passValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.IS_DEL
     *
     * @return the value of t_ydzf_monitor_templet.IS_DEL
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.IS_DEL
     *
     * @param isDel the value for t_ydzf_monitor_templet.IS_DEL
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.CREATE_DATE
     *
     * @return the value of t_ydzf_monitor_templet.CREATE_DATE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public Timestamp getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.CREATE_DATE
     *
     * @param createDate the value for t_ydzf_monitor_templet.CREATE_DATE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.CREATE_USERID
     *
     * @return the value of t_ydzf_monitor_templet.CREATE_USERID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public Integer getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.CREATE_USERID
     *
     * @param createUserid the value for t_ydzf_monitor_templet.CREATE_USERID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setCreateUserid(Integer createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.UPDATE_DATE
     *
     * @return the value of t_ydzf_monitor_templet.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public Timestamp getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.UPDATE_DATE
     *
     * @param updateDate the value for t_ydzf_monitor_templet.UPDATE_DATE
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_monitor_templet.UPDATE_USERID
     *
     * @return the value of t_ydzf_monitor_templet.UPDATE_USERID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_monitor_templet.UPDATE_USERID
     *
     * @param updateUserid the value for t_ydzf_monitor_templet.UPDATE_USERID
     *
     * @mbggenerated Sat Apr 23 01:52:01 GMT+08:00 2016
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }
}