package com.bdx.rainbow.mapp.model.bean;

import java.sql.Timestamp;

public class TYdzfInspectCaseWitnessesMB {
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.INSPECT_CASE_WITNESSES_ID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private Integer inspectCaseWitnessesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.INSPECT_CASE_ID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private Integer inspectCaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.WITNESSES_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private Timestamp witnessesDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.WITNESSES_VIDEO_IDS
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private String witnessesVideoIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.WITNESSES_RESULT
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private String witnessesResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.WITNESSES_ADVICE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private String witnessesAdvice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.REMARK
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.CREATE_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private Timestamp createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.CREATE_USERID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private Integer createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.UPDATE_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private Timestamp updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ydzf_inspect_case_witnesses.UPDATE_USERID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    private Integer updateUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.INSPECT_CASE_WITNESSES_ID
     *
     * @return the value of t_ydzf_inspect_case_witnesses.INSPECT_CASE_WITNESSES_ID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Integer getInspectCaseWitnessesId() {
        return inspectCaseWitnessesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.INSPECT_CASE_WITNESSES_ID
     *
     * @param inspectCaseWitnessesId the value for t_ydzf_inspect_case_witnesses.INSPECT_CASE_WITNESSES_ID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setInspectCaseWitnessesId(Integer inspectCaseWitnessesId) {
        this.inspectCaseWitnessesId = inspectCaseWitnessesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.INSPECT_CASE_ID
     *
     * @return the value of t_ydzf_inspect_case_witnesses.INSPECT_CASE_ID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Integer getInspectCaseId() {
        return inspectCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.INSPECT_CASE_ID
     *
     * @param inspectCaseId the value for t_ydzf_inspect_case_witnesses.INSPECT_CASE_ID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setInspectCaseId(Integer inspectCaseId) {
        this.inspectCaseId = inspectCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.WITNESSES_DATE
     *
     * @return the value of t_ydzf_inspect_case_witnesses.WITNESSES_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Timestamp getWitnessesDate() {
        return witnessesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.WITNESSES_DATE
     *
     * @param witnessesDate the value for t_ydzf_inspect_case_witnesses.WITNESSES_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setWitnessesDate(Timestamp witnessesDate) {
        this.witnessesDate = witnessesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.WITNESSES_VIDEO_IDS
     *
     * @return the value of t_ydzf_inspect_case_witnesses.WITNESSES_VIDEO_IDS
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public String getWitnessesVideoIds() {
        return witnessesVideoIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.WITNESSES_VIDEO_IDS
     *
     * @param witnessesVideoIds the value for t_ydzf_inspect_case_witnesses.WITNESSES_VIDEO_IDS
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setWitnessesVideoIds(String witnessesVideoIds) {
        this.witnessesVideoIds = witnessesVideoIds == null ? null : witnessesVideoIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.WITNESSES_RESULT
     *
     * @return the value of t_ydzf_inspect_case_witnesses.WITNESSES_RESULT
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public String getWitnessesResult() {
        return witnessesResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.WITNESSES_RESULT
     *
     * @param witnessesResult the value for t_ydzf_inspect_case_witnesses.WITNESSES_RESULT
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setWitnessesResult(String witnessesResult) {
        this.witnessesResult = witnessesResult == null ? null : witnessesResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.WITNESSES_ADVICE
     *
     * @return the value of t_ydzf_inspect_case_witnesses.WITNESSES_ADVICE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public String getWitnessesAdvice() {
        return witnessesAdvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.WITNESSES_ADVICE
     *
     * @param witnessesAdvice the value for t_ydzf_inspect_case_witnesses.WITNESSES_ADVICE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setWitnessesAdvice(String witnessesAdvice) {
        this.witnessesAdvice = witnessesAdvice == null ? null : witnessesAdvice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.REMARK
     *
     * @return the value of t_ydzf_inspect_case_witnesses.REMARK
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.REMARK
     *
     * @param remark the value for t_ydzf_inspect_case_witnesses.REMARK
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.CREATE_DATE
     *
     * @return the value of t_ydzf_inspect_case_witnesses.CREATE_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Timestamp getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.CREATE_DATE
     *
     * @param createDate the value for t_ydzf_inspect_case_witnesses.CREATE_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.CREATE_USERID
     *
     * @return the value of t_ydzf_inspect_case_witnesses.CREATE_USERID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Integer getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.CREATE_USERID
     *
     * @param createUserid the value for t_ydzf_inspect_case_witnesses.CREATE_USERID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setCreateUserid(Integer createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.UPDATE_DATE
     *
     * @return the value of t_ydzf_inspect_case_witnesses.UPDATE_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Timestamp getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.UPDATE_DATE
     *
     * @param updateDate the value for t_ydzf_inspect_case_witnesses.UPDATE_DATE
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ydzf_inspect_case_witnesses.UPDATE_USERID
     *
     * @return the value of t_ydzf_inspect_case_witnesses.UPDATE_USERID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ydzf_inspect_case_witnesses.UPDATE_USERID
     *
     * @param updateUserid the value for t_ydzf_inspect_case_witnesses.UPDATE_USERID
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }
}