package com.bdx.rainbow.entity.urs;

public class SysRoleHisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_his.ROLE_ID
     *
     * @mbggenerated Tue Jan 19 22:26:20 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_his.BUSSIN4
     *
     * @mbggenerated Tue Jan 19 22:26:20 CST 2016
     */
    private Integer bussin4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_his.ROLE_ID
     *
     * @return the value of t_sys_role_his.ROLE_ID
     *
     * @mbggenerated Tue Jan 19 22:26:20 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_his.ROLE_ID
     *
     * @param roleId the value for t_sys_role_his.ROLE_ID
     *
     * @mbggenerated Tue Jan 19 22:26:20 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_his.BUSSIN4
     *
     * @return the value of t_sys_role_his.BUSSIN4
     *
     * @mbggenerated Tue Jan 19 22:26:20 CST 2016
     */
    public Integer getBussin4() {
        return bussin4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_his.BUSSIN4
     *
     * @param bussin4 the value for t_sys_role_his.BUSSIN4
     *
     * @mbggenerated Tue Jan 19 22:26:20 CST 2016
     */
    public void setBussin4(Integer bussin4) {
        this.bussin4 = bussin4;
    }
}