package com.bdx.rainbow.entity.urs;

public class SysViews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_views.P_KEY
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    private String pKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_views.P_VALUE
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    private String pValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_views.P_DESC
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    private String pDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_sys_views.P_P_VALUE
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    private String pPValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_views.P_KEY
     *
     * @return the value of v_sys_views.P_KEY
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    public String getpKey() {
        return pKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_views.P_KEY
     *
     * @param pKey the value for v_sys_views.P_KEY
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    public void setpKey(String pKey) {
        this.pKey = pKey == null ? null : pKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_views.P_VALUE
     *
     * @return the value of v_sys_views.P_VALUE
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    public String getpValue() {
        return pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_views.P_VALUE
     *
     * @param pValue the value for v_sys_views.P_VALUE
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    public void setpValue(String pValue) {
        this.pValue = pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_views.P_DESC
     *
     * @return the value of v_sys_views.P_DESC
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    public String getpDesc() {
        return pDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_views.P_DESC
     *
     * @param pDesc the value for v_sys_views.P_DESC
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    public void setpDesc(String pDesc) {
        this.pDesc = pDesc == null ? null : pDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_sys_views.P_P_VALUE
     *
     * @return the value of v_sys_views.P_P_VALUE
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    public String getpPValue() {
        return pPValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_sys_views.P_P_VALUE
     *
     * @param pPValue the value for v_sys_views.P_P_VALUE
     *
     * @mbggenerated Mon Feb 01 10:18:50 CST 2016
     */
    public void setpPValue(String pPValue) {
        this.pPValue = pPValue == null ? null : pPValue.trim();
    }
}