package com.bdx.rainbow.spsy.dal.ibatis.dao;

import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginProducerStockOut;
import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginProducerStockOutExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TOriginProducerStockOutDAOImpl extends SqlMapClientDaoSupport implements TOriginProducerStockOutDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public TOriginProducerStockOutDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public int countByExample(TOriginProducerStockOutExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_origin_producer_stock_out.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public int deleteByExample(TOriginProducerStockOutExample example) {
        int rows = getSqlMapClientTemplate().delete("t_origin_producer_stock_out.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public int deleteByPrimaryKey(Integer operationOutId) {
        TOriginProducerStockOut _key = new TOriginProducerStockOut();
        _key.setOperationOutId(operationOutId);
        int rows = getSqlMapClientTemplate().delete("t_origin_producer_stock_out.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public Integer insert(TOriginProducerStockOut record) {
        Object newKey = getSqlMapClientTemplate().insert("t_origin_producer_stock_out.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public Integer insertSelective(TOriginProducerStockOut record) {
        Object newKey = getSqlMapClientTemplate().insert("t_origin_producer_stock_out.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public List<TOriginProducerStockOut> selectByExample(TOriginProducerStockOutExample example) {
        List<TOriginProducerStockOut> list = getSqlMapClientTemplate().queryForList("t_origin_producer_stock_out.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public TOriginProducerStockOut selectByPrimaryKey(Integer operationOutId) {
        TOriginProducerStockOut _key = new TOriginProducerStockOut();
        _key.setOperationOutId(operationOutId);
        TOriginProducerStockOut record = (TOriginProducerStockOut) getSqlMapClientTemplate().queryForObject("t_origin_producer_stock_out.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public int updateByExampleSelective(TOriginProducerStockOut record, TOriginProducerStockOutExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_origin_producer_stock_out.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public int updateByExample(TOriginProducerStockOut record, TOriginProducerStockOutExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_origin_producer_stock_out.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public int updateByPrimaryKeySelective(TOriginProducerStockOut record) {
        int rows = getSqlMapClientTemplate().update("t_origin_producer_stock_out.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    public int updateByPrimaryKey(TOriginProducerStockOut record) {
        int rows = getSqlMapClientTemplate().update("t_origin_producer_stock_out.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_origin_producer_stock_out
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends TOriginProducerStockOutExample {
        private Object record;

        public UpdateByExampleParms(Object record, TOriginProducerStockOutExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}