package com.bdx.rainbow.spsy.dal.ibatis.dao;

import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginPurchaseInfo;
import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginPurchaseInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TOriginPurchaseInfoDAOImpl extends SqlMapClientDaoSupport implements TOriginPurchaseInfoDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public TOriginPurchaseInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public int countByExample(TOriginPurchaseInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_origin_purchase_info.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public int deleteByExample(TOriginPurchaseInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("t_origin_purchase_info.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public int deleteByPrimaryKey(Integer purchaseId) {
        TOriginPurchaseInfo _key = new TOriginPurchaseInfo();
        _key.setPurchaseId(purchaseId);
        int rows = getSqlMapClientTemplate().delete("t_origin_purchase_info.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public Integer insert(TOriginPurchaseInfo record) {
        Object newKey = getSqlMapClientTemplate().insert("t_origin_purchase_info.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public Integer insertSelective(TOriginPurchaseInfo record) {
        Object newKey = getSqlMapClientTemplate().insert("t_origin_purchase_info.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public List<TOriginPurchaseInfo> selectByExample(TOriginPurchaseInfoExample example) {
        List<TOriginPurchaseInfo> list = getSqlMapClientTemplate().queryForList("t_origin_purchase_info.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public TOriginPurchaseInfo selectByPrimaryKey(Integer purchaseId) {
        TOriginPurchaseInfo _key = new TOriginPurchaseInfo();
        _key.setPurchaseId(purchaseId);
        TOriginPurchaseInfo record = (TOriginPurchaseInfo) getSqlMapClientTemplate().queryForObject("t_origin_purchase_info.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public int updateByExampleSelective(TOriginPurchaseInfo record, TOriginPurchaseInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_origin_purchase_info.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public int updateByExample(TOriginPurchaseInfo record, TOriginPurchaseInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_origin_purchase_info.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public int updateByPrimaryKeySelective(TOriginPurchaseInfo record) {
        int rows = getSqlMapClientTemplate().update("t_origin_purchase_info.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    public int updateByPrimaryKey(TOriginPurchaseInfo record) {
        int rows = getSqlMapClientTemplate().update("t_origin_purchase_info.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_origin_purchase_info
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends TOriginPurchaseInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, TOriginPurchaseInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}