package com.bdx.rainbow.spsy.dal.ibatis.dao;

import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginSkuAgencyRelation;
import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginSkuAgencyRelationExample;
import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginSkuAgencyRelationKey;
import java.util.List;

public interface TOriginSkuAgencyRelationDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    int countByExample(TOriginSkuAgencyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    int deleteByExample(TOriginSkuAgencyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TOriginSkuAgencyRelationKey _key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    void insert(TOriginSkuAgencyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    void insertSelective(TOriginSkuAgencyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    List<TOriginSkuAgencyRelation> selectByExample(TOriginSkuAgencyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    TOriginSkuAgencyRelation selectByPrimaryKey(TOriginSkuAgencyRelationKey _key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(TOriginSkuAgencyRelation record, TOriginSkuAgencyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    int updateByExample(TOriginSkuAgencyRelation record, TOriginSkuAgencyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOriginSkuAgencyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_sku_agency_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOriginSkuAgencyRelation record);
}