package com.bdx.rainbow.spsy.dal.ibatis.dao;

import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginMaterialInfo;
import com.bdx.rainbow.spsy.dal.ibatis.model.TOriginMaterialInfoExample;
import java.util.List;

public interface TOriginMaterialInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    int countByExample(TOriginMaterialInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    int deleteByExample(TOriginMaterialInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    Integer insert(TOriginMaterialInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    Integer insertSelective(TOriginMaterialInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    List<TOriginMaterialInfo> selectByExample(TOriginMaterialInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    TOriginMaterialInfo selectByPrimaryKey(Integer materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(TOriginMaterialInfo record, TOriginMaterialInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    int updateByExample(TOriginMaterialInfo record, TOriginMaterialInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOriginMaterialInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_origin_material_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOriginMaterialInfo record);
}