package com.bdx.rainbow.mapper.ydzf;

import com.bdx.rainbow.entity.ydzf.TYdzfInspectCaseEvidence;
import com.bdx.rainbow.entity.ydzf.TYdzfInspectCaseEvidenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TYdzfInspectCaseEvidenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int countByExample(TYdzfInspectCaseEvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int deleteByExample(TYdzfInspectCaseEvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer inspectCaseEvidenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int insert(TYdzfInspectCaseEvidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int insertSelective(TYdzfInspectCaseEvidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    List<TYdzfInspectCaseEvidence> selectByExample(TYdzfInspectCaseEvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    TYdzfInspectCaseEvidence selectByPrimaryKey(Integer inspectCaseEvidenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") TYdzfInspectCaseEvidence record, @Param("example") TYdzfInspectCaseEvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByExample(@Param("record") TYdzfInspectCaseEvidence record, @Param("example") TYdzfInspectCaseEvidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(TYdzfInspectCaseEvidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByPrimaryKey(TYdzfInspectCaseEvidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_evidence
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    void insertBatch(List<TYdzfInspectCaseEvidence> recordLst);
}