package com.bdx.rainbow.mapper.ydzf;

import com.bdx.rainbow.entity.ydzf.TYdzfInspectCaseFinish;
import com.bdx.rainbow.entity.ydzf.TYdzfInspectCaseFinishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TYdzfInspectCaseFinishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int countByExample(TYdzfInspectCaseFinishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int deleteByExample(TYdzfInspectCaseFinishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer inspectCaseFinishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int insert(TYdzfInspectCaseFinish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int insertSelective(TYdzfInspectCaseFinish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    List<TYdzfInspectCaseFinish> selectByExample(TYdzfInspectCaseFinishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    TYdzfInspectCaseFinish selectByPrimaryKey(Integer inspectCaseFinishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") TYdzfInspectCaseFinish record, @Param("example") TYdzfInspectCaseFinishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByExample(@Param("record") TYdzfInspectCaseFinish record, @Param("example") TYdzfInspectCaseFinishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(TYdzfInspectCaseFinish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByPrimaryKey(TYdzfInspectCaseFinish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_finish
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    void insertBatch(List<TYdzfInspectCaseFinish> recordLst);
}