package com.bdx.rainbow.mapper.ydzf;

import com.bdx.rainbow.entity.ydzf.TYdzfInspectCaseWitnesses;
import com.bdx.rainbow.entity.ydzf.TYdzfInspectCaseWitnessesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TYdzfInspectCaseWitnessesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int countByExample(TYdzfInspectCaseWitnessesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int deleteByExample(TYdzfInspectCaseWitnessesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer inspectCaseWitnessesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int insert(TYdzfInspectCaseWitnesses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int insertSelective(TYdzfInspectCaseWitnesses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    List<TYdzfInspectCaseWitnesses> selectByExample(TYdzfInspectCaseWitnessesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    TYdzfInspectCaseWitnesses selectByPrimaryKey(Integer inspectCaseWitnessesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") TYdzfInspectCaseWitnesses record, @Param("example") TYdzfInspectCaseWitnessesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByExample(@Param("record") TYdzfInspectCaseWitnesses record, @Param("example") TYdzfInspectCaseWitnessesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(TYdzfInspectCaseWitnesses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    int updateByPrimaryKey(TYdzfInspectCaseWitnesses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ydzf_inspect_case_witnesses
     *
     * @mbggenerated Mon Apr 11 23:56:20 GMT+08:00 2016
     */
    void insertBatch(List<TYdzfInspectCaseWitnesses> recordLst);
}