package com.bdx.rainbow.entity.etl;

import java.sql.Timestamp;

public class Cmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.GMP_ID
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private Long gmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.PROVINCE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.GMP_NO
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String gmpNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.CORP_NAME
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.CORP_ADDRESS
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String corpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.AUTH_RANGE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String authRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.ISSUE_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private Timestamp issueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.VALID_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private Timestamp validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.EX_ISSUE_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private Timestamp exIssueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.EX_VALID_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private Timestamp exValidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.EX_AUTH_RANGE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String exAuthRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.CREATETIME
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.REMARK
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gmp.VERSION
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.GMP_ID
     *
     * @return the value of gmp.GMP_ID
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public Long getGmpId() {
        return gmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.GMP_ID
     *
     * @param gmpId the value for gmp.GMP_ID
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setGmpId(Long gmpId) {
        this.gmpId = gmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.PROVINCE
     *
     * @return the value of gmp.PROVINCE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.PROVINCE
     *
     * @param province the value for gmp.PROVINCE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.GMP_NO
     *
     * @return the value of gmp.GMP_NO
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getGmpNo() {
        return gmpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.GMP_NO
     *
     * @param gmpNo the value for gmp.GMP_NO
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setGmpNo(String gmpNo) {
        this.gmpNo = gmpNo == null ? null : gmpNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.CORP_NAME
     *
     * @return the value of gmp.CORP_NAME
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.CORP_NAME
     *
     * @param corpName the value for gmp.CORP_NAME
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.CORP_ADDRESS
     *
     * @return the value of gmp.CORP_ADDRESS
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getCorpAddress() {
        return corpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.CORP_ADDRESS
     *
     * @param corpAddress the value for gmp.CORP_ADDRESS
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setCorpAddress(String corpAddress) {
        this.corpAddress = corpAddress == null ? null : corpAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.AUTH_RANGE
     *
     * @return the value of gmp.AUTH_RANGE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getAuthRange() {
        return authRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.AUTH_RANGE
     *
     * @param authRange the value for gmp.AUTH_RANGE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setAuthRange(String authRange) {
        this.authRange = authRange == null ? null : authRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.ISSUE_DATE
     *
     * @return the value of gmp.ISSUE_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public Timestamp getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.ISSUE_DATE
     *
     * @param issueDate the value for gmp.ISSUE_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setIssueDate(Timestamp issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.VALID_DATE
     *
     * @return the value of gmp.VALID_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public Timestamp getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.VALID_DATE
     *
     * @param validDate the value for gmp.VALID_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setValidDate(Timestamp validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.EX_ISSUE_DATE
     *
     * @return the value of gmp.EX_ISSUE_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public Timestamp getExIssueDate() {
        return exIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.EX_ISSUE_DATE
     *
     * @param exIssueDate the value for gmp.EX_ISSUE_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setExIssueDate(Timestamp exIssueDate) {
        this.exIssueDate = exIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.EX_VALID_DATE
     *
     * @return the value of gmp.EX_VALID_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public Timestamp getExValidDate() {
        return exValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.EX_VALID_DATE
     *
     * @param exValidDate the value for gmp.EX_VALID_DATE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setExValidDate(Timestamp exValidDate) {
        this.exValidDate = exValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.EX_AUTH_RANGE
     *
     * @return the value of gmp.EX_AUTH_RANGE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getExAuthRange() {
        return exAuthRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.EX_AUTH_RANGE
     *
     * @param exAuthRange the value for gmp.EX_AUTH_RANGE
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setExAuthRange(String exAuthRange) {
        this.exAuthRange = exAuthRange == null ? null : exAuthRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.CREATETIME
     *
     * @return the value of gmp.CREATETIME
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.CREATETIME
     *
     * @param createtime the value for gmp.CREATETIME
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.REMARK
     *
     * @return the value of gmp.REMARK
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.REMARK
     *
     * @param remark the value for gmp.REMARK
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gmp.VERSION
     *
     * @return the value of gmp.VERSION
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gmp.VERSION
     *
     * @param version the value for gmp.VERSION
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}