package com.bdx.rainbow.entity.etl;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class InspectionAgencyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    protected String suffix = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    protected int limitClauseStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    protected int limitClauseCount = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public InspectionAgencyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setLimitClauseStart(int limitClauseStart) {
        this.limitClauseStart=limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public int getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public void setLimitClauseCount(int limitClauseCount) {
        this.limitClauseCount=limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public int getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInspecNoIsNull() {
            addCriterion("INSPEC_NO is null");
            return (Criteria) this;
        }

        public Criteria andInspecNoIsNotNull() {
            addCriterion("INSPEC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andInspecNoEqualTo(BigDecimal value) {
            addCriterion("INSPEC_NO =", value, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoNotEqualTo(BigDecimal value) {
            addCriterion("INSPEC_NO <>", value, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoGreaterThan(BigDecimal value) {
            addCriterion("INSPEC_NO >", value, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INSPEC_NO >=", value, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoLessThan(BigDecimal value) {
            addCriterion("INSPEC_NO <", value, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INSPEC_NO <=", value, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoIn(List<BigDecimal> values) {
            addCriterion("INSPEC_NO in", values, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoNotIn(List<BigDecimal> values) {
            addCriterion("INSPEC_NO not in", values, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INSPEC_NO between", value1, value2, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andInspecNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INSPEC_NO not between", value1, value2, "inspecNo");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("PROVINCE in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("PROVINCE not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("SKU_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("SKU_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(String value) {
            addCriterion("SKU_NAME =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(String value) {
            addCriterion("SKU_NAME <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(String value) {
            addCriterion("SKU_NAME >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_NAME >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(String value) {
            addCriterion("SKU_NAME <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(String value) {
            addCriterion("SKU_NAME <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLike(String value) {
            addCriterion("SKU_NAME like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotLike(String value) {
            addCriterion("SKU_NAME not like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<String> values) {
            addCriterion("SKU_NAME in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<String> values) {
            addCriterion("SKU_NAME not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(String value1, String value2) {
            addCriterion("SKU_NAME between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(String value1, String value2) {
            addCriterion("SKU_NAME not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andInspecTypeIsNull() {
            addCriterion("INSPEC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andInspecTypeIsNotNull() {
            addCriterion("INSPEC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andInspecTypeEqualTo(String value) {
            addCriterion("INSPEC_TYPE =", value, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeNotEqualTo(String value) {
            addCriterion("INSPEC_TYPE <>", value, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeGreaterThan(String value) {
            addCriterion("INSPEC_TYPE >", value, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeGreaterThanOrEqualTo(String value) {
            addCriterion("INSPEC_TYPE >=", value, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeLessThan(String value) {
            addCriterion("INSPEC_TYPE <", value, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeLessThanOrEqualTo(String value) {
            addCriterion("INSPEC_TYPE <=", value, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeLike(String value) {
            addCriterion("INSPEC_TYPE like", value, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeNotLike(String value) {
            addCriterion("INSPEC_TYPE not like", value, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeIn(List<String> values) {
            addCriterion("INSPEC_TYPE in", values, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeNotIn(List<String> values) {
            addCriterion("INSPEC_TYPE not in", values, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeBetween(String value1, String value2) {
            addCriterion("INSPEC_TYPE between", value1, value2, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecTypeNotBetween(String value1, String value2) {
            addCriterion("INSPEC_TYPE not between", value1, value2, "inspecType");
            return (Criteria) this;
        }

        public Criteria andInspecStandardIsNull() {
            addCriterion("INSPEC_STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andInspecStandardIsNotNull() {
            addCriterion("INSPEC_STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andInspecStandardEqualTo(String value) {
            addCriterion("INSPEC_STANDARD =", value, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardNotEqualTo(String value) {
            addCriterion("INSPEC_STANDARD <>", value, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardGreaterThan(String value) {
            addCriterion("INSPEC_STANDARD >", value, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardGreaterThanOrEqualTo(String value) {
            addCriterion("INSPEC_STANDARD >=", value, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardLessThan(String value) {
            addCriterion("INSPEC_STANDARD <", value, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardLessThanOrEqualTo(String value) {
            addCriterion("INSPEC_STANDARD <=", value, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardLike(String value) {
            addCriterion("INSPEC_STANDARD like", value, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardNotLike(String value) {
            addCriterion("INSPEC_STANDARD not like", value, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardIn(List<String> values) {
            addCriterion("INSPEC_STANDARD in", values, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardNotIn(List<String> values) {
            addCriterion("INSPEC_STANDARD not in", values, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardBetween(String value1, String value2) {
            addCriterion("INSPEC_STANDARD between", value1, value2, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andInspecStandardNotBetween(String value1, String value2) {
            addCriterion("INSPEC_STANDARD not between", value1, value2, "inspecStandard");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiIsNull() {
            addCriterion("STANDARD_ORGI is null");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiIsNotNull() {
            addCriterion("STANDARD_ORGI is not null");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiEqualTo(String value) {
            addCriterion("STANDARD_ORGI =", value, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiNotEqualTo(String value) {
            addCriterion("STANDARD_ORGI <>", value, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiGreaterThan(String value) {
            addCriterion("STANDARD_ORGI >", value, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiGreaterThanOrEqualTo(String value) {
            addCriterion("STANDARD_ORGI >=", value, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiLessThan(String value) {
            addCriterion("STANDARD_ORGI <", value, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiLessThanOrEqualTo(String value) {
            addCriterion("STANDARD_ORGI <=", value, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiLike(String value) {
            addCriterion("STANDARD_ORGI like", value, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiNotLike(String value) {
            addCriterion("STANDARD_ORGI not like", value, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiIn(List<String> values) {
            addCriterion("STANDARD_ORGI in", values, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiNotIn(List<String> values) {
            addCriterion("STANDARD_ORGI not in", values, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiBetween(String value1, String value2) {
            addCriterion("STANDARD_ORGI between", value1, value2, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andStandardOrgiNotBetween(String value1, String value2) {
            addCriterion("STANDARD_ORGI not between", value1, value2, "standardOrgi");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNull() {
            addCriterion("POSTCODE is null");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNotNull() {
            addCriterion("POSTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPostcodeEqualTo(String value) {
            addCriterion("POSTCODE =", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotEqualTo(String value) {
            addCriterion("POSTCODE <>", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThan(String value) {
            addCriterion("POSTCODE >", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("POSTCODE >=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThan(String value) {
            addCriterion("POSTCODE <", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThanOrEqualTo(String value) {
            addCriterion("POSTCODE <=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLike(String value) {
            addCriterion("POSTCODE like", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotLike(String value) {
            addCriterion("POSTCODE not like", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeIn(List<String> values) {
            addCriterion("POSTCODE in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotIn(List<String> values) {
            addCriterion("POSTCODE not in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeBetween(String value1, String value2) {
            addCriterion("POSTCODE between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotBetween(String value1, String value2) {
            addCriterion("POSTCODE not between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andLinkmanIsNull() {
            addCriterion("LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andLinkmanIsNotNull() {
            addCriterion("LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andLinkmanEqualTo(String value) {
            addCriterion("LINKMAN =", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotEqualTo(String value) {
            addCriterion("LINKMAN <>", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanGreaterThan(String value) {
            addCriterion("LINKMAN >", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("LINKMAN >=", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLessThan(String value) {
            addCriterion("LINKMAN <", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLessThanOrEqualTo(String value) {
            addCriterion("LINKMAN <=", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLike(String value) {
            addCriterion("LINKMAN like", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotLike(String value) {
            addCriterion("LINKMAN not like", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanIn(List<String> values) {
            addCriterion("LINKMAN in", values, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotIn(List<String> values) {
            addCriterion("LINKMAN not in", values, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanBetween(String value1, String value2) {
            addCriterion("LINKMAN between", value1, value2, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotBetween(String value1, String value2) {
            addCriterion("LINKMAN not between", value1, value2, "linkman");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("PHONE like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("PHONE not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andFaxIsNull() {
            addCriterion("FAX is null");
            return (Criteria) this;
        }

        public Criteria andFaxIsNotNull() {
            addCriterion("FAX is not null");
            return (Criteria) this;
        }

        public Criteria andFaxEqualTo(String value) {
            addCriterion("FAX =", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotEqualTo(String value) {
            addCriterion("FAX <>", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThan(String value) {
            addCriterion("FAX >", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThanOrEqualTo(String value) {
            addCriterion("FAX >=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThan(String value) {
            addCriterion("FAX <", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThanOrEqualTo(String value) {
            addCriterion("FAX <=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLike(String value) {
            addCriterion("FAX like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotLike(String value) {
            addCriterion("FAX not like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxIn(List<String> values) {
            addCriterion("FAX in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotIn(List<String> values) {
            addCriterion("FAX not in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxBetween(String value1, String value2) {
            addCriterion("FAX between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotBetween(String value1, String value2) {
            addCriterion("FAX not between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andInspecIdIsNull() {
            addCriterion("INSPEC_ID is null");
            return (Criteria) this;
        }

        public Criteria andInspecIdIsNotNull() {
            addCriterion("INSPEC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInspecIdEqualTo(Long value) {
            addCriterion("INSPEC_ID =", value, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdNotEqualTo(Long value) {
            addCriterion("INSPEC_ID <>", value, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdGreaterThan(Long value) {
            addCriterion("INSPEC_ID >", value, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("INSPEC_ID >=", value, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdLessThan(Long value) {
            addCriterion("INSPEC_ID <", value, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdLessThanOrEqualTo(Long value) {
            addCriterion("INSPEC_ID <=", value, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdIn(List<Long> values) {
            addCriterion("INSPEC_ID in", values, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdNotIn(List<Long> values) {
            addCriterion("INSPEC_ID not in", values, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdBetween(Long value1, Long value2) {
            addCriterion("INSPEC_ID between", value1, value2, "inspecId");
            return (Criteria) this;
        }

        public Criteria andInspecIdNotBetween(Long value1, Long value2) {
            addCriterion("INSPEC_ID not between", value1, value2, "inspecId");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("VERSION like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("VERSION not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspection_agency
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 29 21:20:40 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspection_agency
     *
     * @mbggenerated Wed Jul 29 21:20:40 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}