package com.bdx.rainbow.entity.sys;

public class SysUserExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_ext.USER_ID
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_ext.EXT_KEY
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    private String extKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_ext.EXT_VALUE
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    private String extValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_ext.USER_ID
     *
     * @return the value of sys_user_ext.USER_ID
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_ext.USER_ID
     *
     * @param userId the value for sys_user_ext.USER_ID
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_ext.EXT_KEY
     *
     * @return the value of sys_user_ext.EXT_KEY
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    public String getExtKey() {
        return extKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_ext.EXT_KEY
     *
     * @param extKey the value for sys_user_ext.EXT_KEY
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    public void setExtKey(String extKey) {
        this.extKey = extKey == null ? null : extKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_ext.EXT_VALUE
     *
     * @return the value of sys_user_ext.EXT_VALUE
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    public String getExtValue() {
        return extValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_ext.EXT_VALUE
     *
     * @param extValue the value for sys_user_ext.EXT_VALUE
     *
     * @mbggenerated Thu Jan 07 15:12:03 CST 2016
     */
    public void setExtValue(String extValue) {
        this.extValue = extValue == null ? null : extValue.trim();
    }
}