package com.bdx.rainbow.mapper.basic.mysql;

import com.bdx.rainbow.entity.basic.mysql.TBasicLawDb;
import com.bdx.rainbow.entity.basic.mysql.TBasicLawDbExample;
import com.bdx.rainbow.entity.basic.mysql.TBasicLawDbWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBasicLawDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int countByExample(TBasicLawDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int deleteByExample(TBasicLawDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int deleteByPrimaryKey(Integer lawId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int insert(TBasicLawDbWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int insertSelective(TBasicLawDbWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    List<TBasicLawDbWithBLOBs> selectByExampleWithBLOBs(TBasicLawDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    List<TBasicLawDb> selectByExample(TBasicLawDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    TBasicLawDbWithBLOBs selectByPrimaryKey(Integer lawId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") TBasicLawDbWithBLOBs record, @Param("example") TBasicLawDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TBasicLawDbWithBLOBs record, @Param("example") TBasicLawDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int updateByExample(@Param("record") TBasicLawDb record, @Param("example") TBasicLawDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int updateByPrimaryKeySelective(TBasicLawDbWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TBasicLawDbWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    int updateByPrimaryKey(TBasicLawDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_law_db
     *
     * @mbggenerated Thu Mar 03 11:43:31 CST 2016
     */
    void insertBatch(List<TBasicLawDbWithBLOBs> recordLst);
}