package com.bdx.rainbow.mapper.basic.mysql;

import com.bdx.rainbow.entity.basic.mysql.TBasicEnterpriseInfo;
import com.bdx.rainbow.entity.basic.mysql.TBasicEnterpriseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBasicEnterpriseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int countByExample(TBasicEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int deleteByExample(TBasicEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int deleteByPrimaryKey(Integer enterpriseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int insert(TBasicEnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int insertSelective(TBasicEnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    List<TBasicEnterpriseInfo> selectByExample(TBasicEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    TBasicEnterpriseInfo selectByPrimaryKey(Integer enterpriseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") TBasicEnterpriseInfo record, @Param("example") TBasicEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int updateByExample(@Param("record") TBasicEnterpriseInfo record, @Param("example") TBasicEnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int updateByPrimaryKeySelective(TBasicEnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    int updateByPrimaryKey(TBasicEnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_enterprise_info
     *
     * @mbggenerated Wed Jan 20 15:55:14 CST 2016
     */
    void insertBatch(List<TBasicEnterpriseInfo> recordLst);
}