package com.bdx.rainbow.mapper.basic.mysql;

import com.bdx.rainbow.entity.basic.mysql.TBasicSkuType;
import com.bdx.rainbow.entity.basic.mysql.TBasicSkuTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBasicSkuTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int countByExample(TBasicSkuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int deleteByExample(TBasicSkuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int deleteByPrimaryKey(Integer skuTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int insert(TBasicSkuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int insertSelective(TBasicSkuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    List<TBasicSkuType> selectByExample(TBasicSkuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    TBasicSkuType selectByPrimaryKey(Integer skuTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") TBasicSkuType record, @Param("example") TBasicSkuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int updateByExample(@Param("record") TBasicSkuType record, @Param("example") TBasicSkuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int updateByPrimaryKeySelective(TBasicSkuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int updateByPrimaryKey(TBasicSkuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_type
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    void insertBatch(List<TBasicSkuType> recordLst);
}