package com.bdx.rainbow.mapper.basic.mysql;

import com.bdx.rainbow.entity.basic.mysql.TBasicSkuMedicalInstrument;
import com.bdx.rainbow.entity.basic.mysql.TBasicSkuMedicalInstrumentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBasicSkuMedicalInstrumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int countByExample(TBasicSkuMedicalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int deleteByExample(TBasicSkuMedicalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int deleteByPrimaryKey(Integer skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int insert(TBasicSkuMedicalInstrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int insertSelective(TBasicSkuMedicalInstrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    List<TBasicSkuMedicalInstrument> selectByExample(TBasicSkuMedicalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    TBasicSkuMedicalInstrument selectByPrimaryKey(Integer skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") TBasicSkuMedicalInstrument record, @Param("example") TBasicSkuMedicalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int updateByExample(@Param("record") TBasicSkuMedicalInstrument record, @Param("example") TBasicSkuMedicalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int updateByPrimaryKeySelective(TBasicSkuMedicalInstrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    int updateByPrimaryKey(TBasicSkuMedicalInstrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_sku_medical_instrument
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    void insertBatch(List<TBasicSkuMedicalInstrument> recordLst);
}