jdbc:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@60.194.3.163:1521:SYJ
  username: orgi
  password: orgi
  maxActive: 3
  maxIdle: 30
  minIdle: 5
  maxWait: 3000
  validationQuery: /* ping */ select 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: -1