package com.bdx.rainbow.entity.basic.mysql;

import java.sql.Timestamp;

public class TBasicFoodAdditiveInspect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.INSPECT_NO
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String inspectNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.PROVINCE_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.INSPECT_NAME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String inspectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.INSPECT_ADDRESS
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String inspectAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.PRODUCT_NAME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.PRODUCT_DETAIL
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String productDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.REQUIRED
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String required;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.INSPECT_STANDARD
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String inspectStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.STANDARD_SOURCE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String standardSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.POST
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.CONTACT
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.TELPHONE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.TAX
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.EMAIL
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.REMARK
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.CREATE_TIME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.CREATER
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.UPDATER
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.AREA_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_food_additive_inspect.COUNTY_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    private String countyCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.INSPECT_NO
     *
     * @return the value of t_basic_food_additive_inspect.INSPECT_NO
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getInspectNo() {
        return inspectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.INSPECT_NO
     *
     * @param inspectNo the value for t_basic_food_additive_inspect.INSPECT_NO
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setInspectNo(String inspectNo) {
        this.inspectNo = inspectNo == null ? null : inspectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.PROVINCE_CODE
     *
     * @return the value of t_basic_food_additive_inspect.PROVINCE_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.PROVINCE_CODE
     *
     * @param provinceCode the value for t_basic_food_additive_inspect.PROVINCE_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.INSPECT_NAME
     *
     * @return the value of t_basic_food_additive_inspect.INSPECT_NAME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getInspectName() {
        return inspectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.INSPECT_NAME
     *
     * @param inspectName the value for t_basic_food_additive_inspect.INSPECT_NAME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setInspectName(String inspectName) {
        this.inspectName = inspectName == null ? null : inspectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.INSPECT_ADDRESS
     *
     * @return the value of t_basic_food_additive_inspect.INSPECT_ADDRESS
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getInspectAddress() {
        return inspectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.INSPECT_ADDRESS
     *
     * @param inspectAddress the value for t_basic_food_additive_inspect.INSPECT_ADDRESS
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setInspectAddress(String inspectAddress) {
        this.inspectAddress = inspectAddress == null ? null : inspectAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.PRODUCT_NAME
     *
     * @return the value of t_basic_food_additive_inspect.PRODUCT_NAME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.PRODUCT_NAME
     *
     * @param productName the value for t_basic_food_additive_inspect.PRODUCT_NAME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.PRODUCT_DETAIL
     *
     * @return the value of t_basic_food_additive_inspect.PRODUCT_DETAIL
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getProductDetail() {
        return productDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.PRODUCT_DETAIL
     *
     * @param productDetail the value for t_basic_food_additive_inspect.PRODUCT_DETAIL
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail == null ? null : productDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.REQUIRED
     *
     * @return the value of t_basic_food_additive_inspect.REQUIRED
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.REQUIRED
     *
     * @param required the value for t_basic_food_additive_inspect.REQUIRED
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setRequired(String required) {
        this.required = required == null ? null : required.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.INSPECT_STANDARD
     *
     * @return the value of t_basic_food_additive_inspect.INSPECT_STANDARD
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getInspectStandard() {
        return inspectStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.INSPECT_STANDARD
     *
     * @param inspectStandard the value for t_basic_food_additive_inspect.INSPECT_STANDARD
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setInspectStandard(String inspectStandard) {
        this.inspectStandard = inspectStandard == null ? null : inspectStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.STANDARD_SOURCE
     *
     * @return the value of t_basic_food_additive_inspect.STANDARD_SOURCE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getStandardSource() {
        return standardSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.STANDARD_SOURCE
     *
     * @param standardSource the value for t_basic_food_additive_inspect.STANDARD_SOURCE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setStandardSource(String standardSource) {
        this.standardSource = standardSource == null ? null : standardSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.POST
     *
     * @return the value of t_basic_food_additive_inspect.POST
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.POST
     *
     * @param post the value for t_basic_food_additive_inspect.POST
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.CONTACT
     *
     * @return the value of t_basic_food_additive_inspect.CONTACT
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.CONTACT
     *
     * @param contact the value for t_basic_food_additive_inspect.CONTACT
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.TELPHONE
     *
     * @return the value of t_basic_food_additive_inspect.TELPHONE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.TELPHONE
     *
     * @param telphone the value for t_basic_food_additive_inspect.TELPHONE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.TAX
     *
     * @return the value of t_basic_food_additive_inspect.TAX
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.TAX
     *
     * @param tax the value for t_basic_food_additive_inspect.TAX
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setTax(String tax) {
        this.tax = tax == null ? null : tax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.EMAIL
     *
     * @return the value of t_basic_food_additive_inspect.EMAIL
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.EMAIL
     *
     * @param email the value for t_basic_food_additive_inspect.EMAIL
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.REMARK
     *
     * @return the value of t_basic_food_additive_inspect.REMARK
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.REMARK
     *
     * @param remark the value for t_basic_food_additive_inspect.REMARK
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.CREATE_TIME
     *
     * @return the value of t_basic_food_additive_inspect.CREATE_TIME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.CREATE_TIME
     *
     * @param createTime the value for t_basic_food_additive_inspect.CREATE_TIME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.CREATER
     *
     * @return the value of t_basic_food_additive_inspect.CREATER
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.CREATER
     *
     * @param creater the value for t_basic_food_additive_inspect.CREATER
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.UPDATE_TIME
     *
     * @return the value of t_basic_food_additive_inspect.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.UPDATE_TIME
     *
     * @param updateTime the value for t_basic_food_additive_inspect.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.UPDATER
     *
     * @return the value of t_basic_food_additive_inspect.UPDATER
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.UPDATER
     *
     * @param updater the value for t_basic_food_additive_inspect.UPDATER
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.AREA_CODE
     *
     * @return the value of t_basic_food_additive_inspect.AREA_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.AREA_CODE
     *
     * @param areaCode the value for t_basic_food_additive_inspect.AREA_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_food_additive_inspect.COUNTY_CODE
     *
     * @return the value of t_basic_food_additive_inspect.COUNTY_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_basic_food_additive_inspect.COUNTY_CODE
     *
     * @param countyCode the value for t_basic_food_additive_inspect.COUNTY_CODE
     *
     * @mbggenerated Wed Jan 20 17:30:41 CST 2016
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }
}