package com.bdx.rainbow.entity.basic.mysql;

import java.sql.Timestamp;

public class TMappUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.USER_ID
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.DEPT_ID
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.USER_NAME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.USER_LOGIN_NAME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private String userLoginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.EMAIL
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.USER_STATUS
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.USER_TYPE
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.CREATER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.CREATE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.UPDATER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private Integer updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.UPDATE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.LOGIN_PWD
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.CHANGE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private Timestamp changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.PWD_ERR_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private Integer pwdErrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mapp_user.ADMIN_USER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    private String adminUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.USER_ID
     *
     * @return the value of t_mapp_user.USER_ID
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.USER_ID
     *
     * @param userId the value for t_mapp_user.USER_ID
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.DEPT_ID
     *
     * @return the value of t_mapp_user.DEPT_ID
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.DEPT_ID
     *
     * @param deptId the value for t_mapp_user.DEPT_ID
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.USER_NAME
     *
     * @return the value of t_mapp_user.USER_NAME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.USER_NAME
     *
     * @param userName the value for t_mapp_user.USER_NAME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.USER_LOGIN_NAME
     *
     * @return the value of t_mapp_user.USER_LOGIN_NAME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public String getUserLoginName() {
        return userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.USER_LOGIN_NAME
     *
     * @param userLoginName the value for t_mapp_user.USER_LOGIN_NAME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setUserLoginName(String userLoginName) {
        this.userLoginName = userLoginName == null ? null : userLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.EMAIL
     *
     * @return the value of t_mapp_user.EMAIL
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.EMAIL
     *
     * @param email the value for t_mapp_user.EMAIL
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.MOBILE_PHONE
     *
     * @return the value of t_mapp_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.MOBILE_PHONE
     *
     * @param mobilePhone the value for t_mapp_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.USER_STATUS
     *
     * @return the value of t_mapp_user.USER_STATUS
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.USER_STATUS
     *
     * @param userStatus the value for t_mapp_user.USER_STATUS
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.USER_TYPE
     *
     * @return the value of t_mapp_user.USER_TYPE
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.USER_TYPE
     *
     * @param userType the value for t_mapp_user.USER_TYPE
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.CREATER
     *
     * @return the value of t_mapp_user.CREATER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.CREATER
     *
     * @param creater the value for t_mapp_user.CREATER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.CREATE_TIME
     *
     * @return the value of t_mapp_user.CREATE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.CREATE_TIME
     *
     * @param createTime the value for t_mapp_user.CREATE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.UPDATER
     *
     * @return the value of t_mapp_user.UPDATER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.UPDATER
     *
     * @param updater the value for t_mapp_user.UPDATER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.UPDATE_TIME
     *
     * @return the value of t_mapp_user.UPDATE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.UPDATE_TIME
     *
     * @param updateTime the value for t_mapp_user.UPDATE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.LOGIN_PWD
     *
     * @return the value of t_mapp_user.LOGIN_PWD
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.LOGIN_PWD
     *
     * @param loginPwd the value for t_mapp_user.LOGIN_PWD
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.CHANGE_TIME
     *
     * @return the value of t_mapp_user.CHANGE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public Timestamp getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.CHANGE_TIME
     *
     * @param changeTime the value for t_mapp_user.CHANGE_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setChangeTime(Timestamp changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.PWD_ERR_TIME
     *
     * @return the value of t_mapp_user.PWD_ERR_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public Integer getPwdErrTime() {
        return pwdErrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.PWD_ERR_TIME
     *
     * @param pwdErrTime the value for t_mapp_user.PWD_ERR_TIME
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setPwdErrTime(Integer pwdErrTime) {
        this.pwdErrTime = pwdErrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mapp_user.ADMIN_USER
     *
     * @return the value of t_mapp_user.ADMIN_USER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public String getAdminUser() {
        return adminUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mapp_user.ADMIN_USER
     *
     * @param adminUser the value for t_mapp_user.ADMIN_USER
     *
     * @mbggenerated Thu Jan 21 15:01:55 CST 2016
     */
    public void setAdminUser(String adminUser) {
        this.adminUser = adminUser == null ? null : adminUser.trim();
    }
}