package com.bdx.rainbow.mapper.etl;

import com.bdx.rainbow.entity.etl.FoodSafetyStandard;
import com.bdx.rainbow.entity.etl.FoodSafetyStandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodSafetyStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int countByExample(FoodSafetyStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int deleteByExample(FoodSafetyStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int insert(FoodSafetyStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int insertSelective(FoodSafetyStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    List<FoodSafetyStandard> selectByExample(FoodSafetyStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    FoodSafetyStandard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") FoodSafetyStandard record, @Param("example") FoodSafetyStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int updateByExample(@Param("record") FoodSafetyStandard record, @Param("example") FoodSafetyStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int updateByPrimaryKeySelective(FoodSafetyStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    int updateByPrimaryKey(FoodSafetyStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_safety_standard
     *
     * @mbggenerated Fri Aug 14 16:55:18 CST 2015
     */
    void insertBatch(List<FoodSafetyStandard> recordLst);
}