package com.bdx.rainbow.mapper.etl;

import com.bdx.rainbow.entity.etl.TABLE2;
import com.bdx.rainbow.entity.etl.TABLE2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TABLE2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int countByExample(TABLE2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int deleteByExample(TABLE2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int insert(TABLE2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int insertSelective(TABLE2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    List<TABLE2> selectByExample(TABLE2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    TABLE2 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") TABLE2 record, @Param("example") TABLE2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByExample(@Param("record") TABLE2 record, @Param("example") TABLE2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByPrimaryKeySelective(TABLE2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByPrimaryKey(TABLE2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    void insertBatch(List<TABLE2> recordLst);
}