package com.bdx.rainbow.mapper.etl;

import com.bdx.rainbow.entity.etl.TABLE84;
import com.bdx.rainbow.entity.etl.TABLE84Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TABLE84Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int countByExample(TABLE84Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int deleteByExample(TABLE84Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int insert(TABLE84 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int insertSelective(TABLE84 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    List<TABLE84> selectByExample(TABLE84Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    TABLE84 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") TABLE84 record, @Param("example") TABLE84Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByExample(@Param("record") TABLE84 record, @Param("example") TABLE84Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByPrimaryKeySelective(TABLE84 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByPrimaryKey(TABLE84 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table84
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    void insertBatch(List<TABLE84> recordLst);
}