package com.bdx.rainbow.mapper.etl;

import com.bdx.rainbow.entity.etl.TABLE65;
import com.bdx.rainbow.entity.etl.TABLE65Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TABLE65Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int countByExample(TABLE65Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int deleteByExample(TABLE65Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int insert(TABLE65 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int insertSelective(TABLE65 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    List<TABLE65> selectByExample(TABLE65Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    TABLE65 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") TABLE65 record, @Param("example") TABLE65Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByExample(@Param("record") TABLE65 record, @Param("example") TABLE65Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByPrimaryKeySelective(TABLE65 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    int updateByPrimaryKey(TABLE65 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table65
     *
     * @mbggenerated Fri Aug 21 15:51:17 CST 2015
     */
    void insertBatch(List<TABLE65> recordLst);
}