package com.bdx.rainbow.ygcf.mapper;

import com.bdx.rainbow.ygcf.entity.Health;
import com.bdx.rainbow.ygcf.entity.HealthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HealthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int countByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int deleteByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer healthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int insert(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int insertSelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    List<Health> selectByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    Health selectByPrimaryKey(Integer healthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Health record, @Param("example") HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Health record, @Param("example") HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_health
     *
     * @mbggenerated
     */
    void insertBatch(List<Health> recordLst);
}