package com.bdx.rainbow.ygcf.mapper;

import com.bdx.rainbow.ygcf.entity.LedgerSterilize;
import com.bdx.rainbow.ygcf.entity.LedgerSterilizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LedgerSterilizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int countByExample(LedgerSterilizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int deleteByExample(LedgerSterilizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sterilizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int insert(LedgerSterilize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int insertSelective(LedgerSterilize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    List<LedgerSterilize> selectByExample(LedgerSterilizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    LedgerSterilize selectByPrimaryKey(Integer sterilizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LedgerSterilize record, @Param("example") LedgerSterilizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LedgerSterilize record, @Param("example") LedgerSterilizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LedgerSterilize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LedgerSterilize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ygcf_ledger_sterilize
     *
     * @mbggenerated
     */
    void insertBatch(List<LedgerSterilize> recordLst);
}